#!/usr/bin/env python3
"""Embed data/web/* into include/WebContent.h as C raw string literals.

Run from the project root after editing any UI file:

    python3 tools/embed_web.py

The firmware serves these embedded strings directly from flash, so no
LittleFS/SPIFFS filesystem upload is required.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "data", "web")
OUT = os.path.join(ROOT, "include", "WebContent.h")

FILES = [
    ("index.html", "INDEX_HTML"),
    ("style.css", "STYLE_CSS"),
    ("app.js", "APP_JS"),
]

DELIM = "rgbwatt"


def emit(name, content):
    if (")" + DELIM + '"') in content:
        raise SystemExit("Delimiter collision in " + name)
    return 'const char {0}[] = R"{1}(\n{2}){1}";\n'.format(name, DELIM, content)


def main():
    parts = [
        "// AUTO-GENERATED by tools/embed_web.py - do not edit by hand.",
        "// Edit data/web/* and re-run the script.",
        "#pragma once",
        "",
    ]
    for fname, var in FILES:
        with open(os.path.join(WEB, fname), "r", encoding="utf-8") as f:
            parts.append(emit(var, f.read()))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
