// AUTO-GENERATED by tools/embed_web.py - do not edit by hand.
// Edit data/web/* and re-run the script.
#pragma once

const char INDEX_HTML[] = R"rgbwatt(
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <title>ZoneGlow</title>
  <link rel="stylesheet" href="/style.css" />
</head>
<body>
  <div class="app">
    <!-- Top bar -->
    <header class="topbar">
      <div class="brand">
        <span class="brand-dot" id="brandDot"></span>
        <div>
          <h1>ZoneGlow</h1>
          <p class="brand-sub">Training Zone Lighting</p>
        </div>
      </div>
      <div class="topbar-right">
        <span class="status-pill" id="statusPill" data-testid="status-pill">
          <span class="pill-dot"></span><span id="statusText">Starting</span>
        </span>
        <div class="theme-switch" id="themeSwitch">
          <button data-theme-val="light" data-testid="theme-light" title="Light">☀</button>
          <button data-theme-val="dark" data-testid="theme-dark" title="Dark">☾</button>
          <button data-theme-val="system" data-testid="theme-system" title="System">◐</button>
        </div>
      </div>
    </header>

    <!-- Nav -->
    <nav class="nav" id="nav">
      <button class="nav-btn active" data-view="dashboard" data-testid="nav-dashboard">Dashboard</button>
      <button class="nav-btn" data-view="devices" data-testid="nav-devices">Devices</button>
      <button class="nav-btn" data-view="zones" data-testid="nav-zones">Zones</button>
      <button class="nav-btn" data-view="settings" data-testid="nav-settings">Settings</button>
      <button class="nav-btn" data-view="about" data-testid="nav-about">About</button>
    </nav>

    <main class="content">
      <!-- Global banners: Hub connection loss + Demo Mode indicator -->
      <div class="conn-banner" id="hubBanner" hidden>Connection to Hub lost — reconnecting…</div>
      <div class="demo-banner" id="demoBanner" hidden>
        <span class="pill-dot"></span><span>Lighting test — cycling through all zones</span>
        <button class="btn small" id="demoExitBtn" data-testid="demo-exit-btn">Stop test</button>
      </div>

      <!-- DASHBOARD -->
      <section class="view active" id="view-dashboard">
        <div class="grid">
          <div class="card power-card" id="powerCard" data-testid="power-card">
            <div class="power-glow" id="powerGlow"></div>
            <div class="power-value"><span id="powerWatts" data-testid="power-watts">0</span><em id="powerUnit">W</em></div>
            <div class="zone-badge" id="zoneBadge" data-testid="zone-badge">
              <span id="zoneNum">Z1</span> · <span id="zoneName">—</span>
            </div>
          </div>

          <div class="card source-mini" data-testid="source-mini">
            <div class="card-label" id="sourceMiniLabel">Power Source</div>
            <div class="source-name" id="dashSourceName">—</div>
            <div class="source-state" id="dashSourceState"><span class="pill-dot"></span><span>Disconnected</span></div>
            <button class="btn demo-btn" id="demoBtn" data-testid="demo-btn">Test Lighting</button>
          </div>

          <div class="card stat-row" data-testid="stat-row">
            <div class="stat"><div class="stat-k" id="statFtpLabel">FTP</div><div class="stat-v"><span id="statFtp">221</span> <span id="statFtpUnit">W</span></div></div>
            <div class="stat"><div class="stat-k">Zones</div><div class="stat-v" id="statZones">7</div></div>
            <div class="stat"><div class="stat-k">Brightness</div><div class="stat-v"><span id="statBright">100</span>%</div></div>
          </div>

        </div>
      </section>

      <!-- DEVICES: one scan lists ALL supported sensors, grouped by type -->
      <section class="view" id="view-devices">
        <div class="card">
          <div class="card-header">
            <div>
              <div class="card-title">Devices</div>
              <p class="muted">All supported BLE sensors. Connecting a Power sensor activates Power mode, a Heart Rate sensor activates Heart Rate mode — only one source is ever active.</p>
            </div>
            <button class="btn primary" id="scanBtn" data-testid="scan-btn">Scan</button>
          </div>

          <div class="device-section">
            <div class="device-section-head">
              <span class="device-section-title power-title">POWER</span>
              <span class="muted" id="powerSavedHint">No saved device</span>
            </div>
            <div class="device-list" id="powerDeviceList" data-testid="power-device-list">
              <div class="empty">No devices yet. Tap Scan to search.</div>
            </div>
          </div>

          <div class="device-section">
            <div class="device-section-head">
              <span class="device-section-title hr-title">HEART RATE</span>
              <span class="muted" id="hrSavedHint">No saved device</span>
            </div>
            <div class="device-list" id="hrDeviceList" data-testid="hr-device-list">
              <div class="empty">No devices yet. Tap Scan to search.</div>
            </div>
          </div>
        </div>
      </section>

      <!-- ZONES: Power and Heart Rate editors, both always visible -->
      <section class="view" id="view-zones">
        <div class="card" id="powerZoneCard">
          <div class="card-header">
            <div>
              <div class="card-title">Power Zones</div>
              <p class="muted" id="powerZoneSub"></p>
            </div>
            <button class="btn" id="resetZonesBtn" data-testid="reset-zones-btn">Reset to FTP defaults</button>
          </div>
          <div class="field-row">
            <div class="field">
              <label>FTP (W)</label>
              <input type="number" id="ftpInput" data-testid="ftp-input" min="50" max="600" />
            </div>
            <div class="field">
              <label>Zone Count</label>
              <select id="zoneCountSel" data-testid="zone-count-select">
                <option value="5">5 Zones</option>
                <option value="6">6 Zones</option>
                <option value="7">7 Zones</option>
              </select>
            </div>
          </div>
          <div id="zoneEditor" class="zone-editor" data-testid="zone-editor"></div>
          <button class="btn primary full" id="saveZonesBtn" data-testid="save-zones-btn">Save Power Zones</button>
        </div>

        <div class="card" id="hrZoneCard">
          <div class="card-header">
            <div>
              <div class="card-title">Heart Rate Zones</div>
              <p class="muted" id="hrZoneNote">5 zones generated from your Max HR. Changing Max HR recalculates them automatically.</p>
            </div>
            <button class="btn" id="resetHrZonesBtn" data-testid="reset-hr-zones-btn">Reset to Max HR defaults</button>
          </div>
          <div class="field-row">
            <div class="field">
              <label>Max HR (BPM)</label>
              <input type="number" id="hrMaxInput" data-testid="hr-max-input" min="100" max="230" />
            </div>
            <div class="field">
              <label>Zone Count</label>
              <input type="text" id="hrZoneCount" value="5 (fixed)" disabled />
            </div>
          </div>
          <div id="hrEditor" class="zone-editor" data-testid="hr-zone-editor"></div>
          <button class="btn primary full" id="saveHrZonesBtn" data-testid="save-hr-zones-btn">Save HR Zones</button>
        </div>
      </section>

      <!-- SETTINGS -->
      <section class="view" id="view-settings">
        <div class="card">
          <div class="card-title">LED Control</div>
          <p class="muted">Choose which measurement controls your lighting. Only one source is active at a time; switching disconnects the current sensor. You can also switch by connecting a device on the Devices page.</p>
          <div class="seg" id="sourceSeg">
            <button data-src="power" class="active" data-testid="src-power">Power</button>
            <button data-src="hr" data-testid="src-hr">Heart Rate</button>
          </div>
        </div>

        <div class="card">
          <div class="card-title">Power Processing</div>
          <div class="field">
            <label>Smoothing <span class="val" id="smoothVal"></span></label>
            <input type="range" min="0" max="100" id="smoothInput" class="slider" data-testid="smoothing-input" />
          </div>
          <div class="field-row">
            <div class="field">
              <label>Data timeout (ms)</label>
              <input type="number" id="timeoutInput" data-testid="timeout-input" min="500" step="500" />
            </div>
            <div class="field">
              <label>Hysteresis (<span id="hysUnit">W</span>)</label>
              <input type="number" id="hysInput" data-testid="hysteresis-input" min="0" />
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-title">LED Strip</div>
          <div class="field-row">
            <div class="field">
              <label>GPIO Pin</label>
              <input type="number" id="ledPinInput" data-testid="led-pin-input" min="0" max="39" />
            </div>
            <div class="field">
              <label>LED Count</label>
              <input type="number" id="ledCountInput" data-testid="led-count-input" min="1" max="1000" />
            </div>
          </div>
          <div class="field-row">
            <div class="field">
              <label>LED Type</label>
              <select id="ledTypeSel" data-testid="led-type-select">
                <option value="WS2812B">WS2812B</option>
                <option value="SK6812">SK6812 (RGBW)</option>
              </select>
            </div>
            <div class="field">
              <label>Effect</label>
              <select id="ledEffectSel" data-testid="led-effect-select">
                <option value="0">Solid</option>
                <option value="1">Breathing</option>
                <option value="2">Comet</option>
              </select>
            </div>
          </div>
          <div class="field">
            <label>Brightness <span class="val" id="brightVal"></span></label>
            <input type="range" min="0" max="100" id="brightInput" class="slider" data-testid="brightness-input" />
          </div>
        </div>

        <div class="card">
          <div class="card-title">BLE</div>
          <div class="field switch-field">
            <label>Auto reconnect to saved source</label>
            <label class="toggle">
              <input type="checkbox" id="autoReconnect" data-testid="auto-reconnect-toggle" />
              <span class="toggle-track"></span>
            </label>
          </div>
          <div class="field switch-field">
            <label>Serial debug logging</label>
            <label class="toggle">
              <input type="checkbox" id="debugToggle" data-testid="debug-toggle" />
              <span class="toggle-track"></span>
            </label>
          </div>
        </div>

        <div class="card">
          <div class="card-title">Wi-Fi</div>
          <p class="muted">Connect the controller to your network. It reboots after saving.</p>
          <div class="field">
            <label>SSID</label>
            <input type="text" id="wifiSsid" data-testid="wifi-ssid-input" placeholder="Network name" />
          </div>
          <div class="field">
            <label>Password</label>
            <input type="password" id="wifiPass" data-testid="wifi-pass-input" placeholder="••••••••" />
          </div>
          <button class="btn primary" id="wifiSaveBtn" data-testid="wifi-save-btn">Save &amp; Reboot</button>
        </div>

        <div class="card">
          <div class="card-title">Firmware Update (OTA)</div>
          <p class="muted">Upload a compiled <code>firmware.bin</code> to flash wirelessly. The device reboots when done — don't close this page during upload.</p>
          <input type="file" id="otaFile" accept=".bin" data-testid="ota-file-input" />
          <div class="ota-progress" id="otaProgress"><div class="ota-bar" id="otaBar"></div></div>
          <button class="btn primary" id="otaBtn" data-testid="ota-upload-btn">Upload &amp; Flash</button>
          <div class="ota-status" id="otaStatus" data-testid="ota-status" hidden></div>
        </div>

        <div class="card danger-card">
          <div class="card-title">Maintenance</div>
          <button class="btn" id="saveSettingsBtn" data-testid="save-settings-btn">Save Settings</button>
          <button class="btn danger" id="factoryBtn" data-testid="factory-reset-btn">Factory Reset</button>
        </div>

        <div class="card">
          <div class="card-title">Configuration Backup</div>
          <p class="muted">Save your zones, LED and processing settings to a JSON file, or restore them from a previous export. Wi-Fi credentials and sensor pairings are never included.</p>
          <div class="field-row">
            <button class="btn" id="exportCfgBtn" data-testid="export-config-btn">Export</button>
            <button class="btn" id="importCfgBtn" data-testid="import-config-btn">Import</button>
            <input type="file" id="importCfgFile" accept=".json,application/json" hidden />
          </div>
          <textarea id="exportOut" class="export-out" readonly hidden data-testid="export-out"></textarea>
          <button class="btn" id="exportCopyBtn" hidden data-testid="export-copy-btn">Copy to clipboard</button>
        </div>
      </section>

      <!-- ABOUT / DIAGNOSTICS -->
      <section class="view" id="view-about">
        <div class="card">
          <div class="card-title">About</div>
          <p class="muted">ZoneGlow — Training Zone Lighting.</p>
          <div class="about-rows">
            <div><span>App version</span><b id="aboutAppVersion" data-testid="about-app-version">—</b></div>
            <div><span>Hub firmware</span><b id="aboutFwVersion">—</b></div>
            <div><span>Hub device ID</span><b id="aboutDeviceId">—</b></div>
          </div>
          <button class="btn" id="onboardingRestartBtn" data-testid="onboarding-restart-btn">Run the getting-started guide</button>
        </div>

        <div class="card">
          <div class="card-title">Diagnostics</div>
          <div class="about-rows">
            <div><span>Hub connection</span><b id="diagWs" data-testid="diag-ws">—</b></div>
            <div><span>Control source</span><b id="diagSource">—</b></div>
            <div><span>Sensor</span><b id="diagSensor">—</b></div>
            <div><span>WebSocket</span><b id="diagWsState">—</b></div>
            <div><span>API</span><b id="diagApi">—</b></div>
          </div>
          <p class="muted">Copy this when contacting support.</p>
          <button class="btn" id="copyDiagBtn" data-testid="copy-diagnostics-btn">Copy diagnostics</button>
        </div>
      </section>
    </main>

    <!-- First-run onboarding overlay (also re-runnable from About) -->
    <div class="onboarding" id="onboarding" hidden data-testid="onboarding">
      <div class="ob-card">
        <button class="ob-skip-btn" id="obSkipBtn" data-testid="ob-skip-btn">Skip setup</button>
        <div class="ob-brand"><span class="ob-dot" id="obDot"></span></div>
        <h2 id="obTitle">Welcome</h2>
        <p class="ob-text" id="obText"></p>
        <div class="ob-body" id="obBody"></div>
        <div class="ob-actions" id="obActions"></div>
      </div>
    </div>

    <div class="toast" id="toast" data-testid="toast"></div>
  </div>
  <script src="/app.js"></script>
</body>
</html>)rgbwatt";

const char STYLE_CSS[] = R"rgbwatt(
:root {
  --bg: #f4f6fb;
  --bg-elev: #ffffff;
  --card: #ffffff;
  --text: #10131a;
  --muted: #6b7280;
  --border: #e5e8f0;
  --accent: #4f46e5;
  --accent-2: #06b6d4;
  --ok: #10b981;
  --warn: #f59e0b;
  --err: #ef4444;
  --shadow: 0 10px 30px rgba(20, 25, 60, 0.08);
  --radius: 18px;
  --font: "Segoe UI", "Helvetica Neue", system-ui, -apple-system, sans-serif;
}
[data-theme="dark"] {
  --bg: #0a0c12;
  --bg-elev: #12151f;
  --card: #151926;
  --text: #eef1f8;
  --muted: #8b93a7;
  --border: #232838;
  --accent: #7c7cff;
  --accent-2: #22d3ee;
  --shadow: 0 12px 40px rgba(0, 0, 0, 0.5);
}

* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { height: 100%; }
body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  -webkit-font-smoothing: antialiased;
  transition: background .3s ease, color .3s ease;
}
.app { max-width: 980px; margin: 0 auto; padding: 0 16px 80px; }

/* Top bar */
.topbar {
  display: flex; align-items: center; justify-content: space-between;
  padding: 20px 4px 12px;
}
.brand { display: flex; align-items: center; gap: 12px; }
.brand-dot {
  width: 40px; height: 40px; border-radius: 12px;
  background: linear-gradient(135deg, var(--accent), var(--accent-2));
  box-shadow: 0 0 24px rgba(124, 124, 255, .5);
  transition: background .4s ease, box-shadow .4s ease;
}
.brand h1 { font-size: 19px; letter-spacing: -.4px; }
.brand-sub { font-size: 12px; color: var(--muted); letter-spacing: 1.5px; text-transform: uppercase; }
.topbar-right { display: flex; align-items: center; gap: 10px; }

.status-pill {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 7px 13px; border-radius: 999px;
  background: var(--bg-elev); border: 1px solid var(--border);
  font-size: 13px; font-weight: 600;
}
.pill-dot { width: 9px; height: 9px; border-radius: 50%; background: var(--muted); }
.status-pill.ok .pill-dot { background: var(--ok); box-shadow: 0 0 10px var(--ok); }
.status-pill.warn .pill-dot { background: var(--warn); box-shadow: 0 0 10px var(--warn); }
.status-pill.err .pill-dot { background: var(--err); box-shadow: 0 0 10px var(--err); }
.status-pill.live .pill-dot { animation: pulse 1.4s infinite; background: var(--ok); }
@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.35} }

.theme-switch { display: flex; background: var(--bg-elev); border: 1px solid var(--border); border-radius: 999px; padding: 3px; }
.theme-switch button {
  border: none; background: transparent; color: var(--muted);
  width: 32px; height: 30px; border-radius: 999px; cursor: pointer; font-size: 15px;
  transition: all .2s;
}
.theme-switch button.active { background: var(--accent); color: #fff; }

/* Segmented control (Control Source) */
.seg { display: flex; gap: 6px; background: var(--bg-elev); border: 1px solid var(--border); padding: 6px; border-radius: 14px; margin-top: 12px; }
.seg button {
  flex: 1; border: none; background: transparent; color: var(--muted);
  padding: 11px 12px; border-radius: 10px; cursor: pointer; font-size: 14px; font-weight: 600;
  transition: all .2s;
}
.seg button.active { background: var(--accent); color: #fff; }

/* Nav */
.nav {
  display: flex; gap: 6px; margin: 6px 0 20px;
  background: var(--bg-elev); border: 1px solid var(--border);
  padding: 6px; border-radius: 14px; overflow-x: auto;
}
.nav-btn {
  flex: 1; min-width: 90px; border: none; background: transparent; color: var(--muted);
  padding: 10px 12px; border-radius: 10px; cursor: pointer; font-size: 14px; font-weight: 600;
  white-space: nowrap; transition: all .2s;
}
.nav-btn.active { background: var(--card); color: var(--text); box-shadow: var(--shadow); }

/* Views */
.view { display: none; animation: fade .35s ease; }
.view.active { display: block; }
@keyframes fade { from { opacity: 0; transform: translateY(8px);} to { opacity: 1; transform: none; } }

.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.card {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 20px; box-shadow: var(--shadow);
  margin-bottom: 16px;
}
.card-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 14px; }
.card-title { font-size: 16px; font-weight: 700; }
.card-label { font-size: 12px; text-transform: uppercase; letter-spacing: 1.2px; color: var(--muted); }
.muted { color: var(--muted); font-size: 13px; line-height: 1.5; }

/* Power card */
.power-card { grid-column: 1 / -1; position: relative; overflow: hidden; text-align: center; padding: 34px 20px 26px; }
.power-glow {
  position: absolute; top: -60px; left: 50%; transform: translateX(-50%);
  width: 320px; height: 320px; border-radius: 50%;
  background: radial-gradient(circle, rgba(124,124,255,.55), transparent 70%);
  filter: blur(30px); transition: background .3s ease; pointer-events: none;
}
.power-value { font-size: 84px; font-weight: 800; line-height: 1; letter-spacing: -3px; position: relative; }
.power-value em { font-size: 28px; font-style: normal; color: var(--muted); margin-left: 6px; font-weight: 600; }
.zone-badge {
  display: inline-block; margin-top: 16px; padding: 8px 18px; border-radius: 999px;
  background: var(--bg-elev); border: 1px solid var(--border); font-weight: 700; font-size: 15px; position: relative;
}

/* Source mini */
.source-mini { display: flex; flex-direction: column; gap: 8px; }
.source-name { font-size: 20px; font-weight: 700; }
.source-state { display: flex; align-items: center; gap: 8px; font-size: 13px; color: var(--muted); }

/* Stat row */
.stat-row { display: flex; justify-content: space-around; align-items: center; }
.stat { text-align: center; }
.stat-k { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 1px; }
.stat-v { font-size: 22px; font-weight: 700; margin-top: 4px; }

/* Buttons */
.btn {
  border: 1px solid var(--border); background: var(--bg-elev); color: var(--text);
  padding: 11px 18px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px;
  transition: all .2s;
}
.btn:hover { transform: translateY(-1px); border-color: var(--accent); }
.btn.primary { background: var(--accent); color: #fff; border-color: var(--accent); }
.btn.primary:hover { filter: brightness(1.08); }
.btn.danger { background: transparent; color: var(--err); border-color: var(--err); }
.btn.full { width: 100%; margin-top: 8px; }

/* Fields */
.field { margin-bottom: 16px; }
.field label { display: block; font-size: 13px; font-weight: 600; margin-bottom: 8px; color: var(--muted); }
.field .val { color: var(--accent); float: right; }
.field-row { display: flex; gap: 14px; }
.field-row .field { flex: 1; }
.switch-field { display: flex; align-items: center; justify-content: space-between; }
.switch-field label:first-child { margin: 0; color: var(--text); font-weight: 600; }
input[type="text"], input[type="number"], input[type="password"], select {
  width: 100%; padding: 12px 14px; border-radius: 12px;
  border: 1px solid var(--border); background: var(--bg-elev); color: var(--text);
  font-size: 15px; font-family: var(--font); outline: none; transition: border .2s;
}
input:focus, select:focus { border-color: var(--accent); }

/* Sliders */
.slider { -webkit-appearance: none; appearance: none; width: 100%; height: 8px; border-radius: 999px; background: var(--border); outline: none; }
.slider::-webkit-slider-thumb { -webkit-appearance: none; width: 22px; height: 22px; border-radius: 50%; background: var(--accent); cursor: pointer; box-shadow: 0 2px 8px rgba(0,0,0,.3); }
.slider::-moz-range-thumb { width: 22px; height: 22px; border: none; border-radius: 50%; background: var(--accent); cursor: pointer; }
.slider:disabled { opacity: .5; }

/* Toggle */
.toggle { position: relative; display: inline-block; width: 46px; height: 26px; }
.toggle input { display: none; }
.toggle-track { position: absolute; inset: 0; background: var(--border); border-radius: 999px; transition: .25s; cursor: pointer; }
.toggle-track:before { content: ""; position: absolute; width: 20px; height: 20px; left: 3px; top: 3px; background: #fff; border-radius: 50%; transition: .25s; }
.toggle input:checked + .toggle-track { background: var(--accent); }
.toggle input:checked + .toggle-track:before { transform: translateX(20px); }

/* Device list */
.device-list { display: flex; flex-direction: column; gap: 10px; }
.empty { color: var(--muted); font-size: 14px; text-align: center; padding: 24px; }
/* Devices page: per-type sections */
.device-section { margin-top: 18px; }
.device-section-head {
  display: flex; align-items: baseline; justify-content: space-between;
  gap: 10px; margin-bottom: 10px;
}
.device-section-title {
  font-size: 12px; font-weight: 800; letter-spacing: 1.4px; color: var(--muted);
}
.power-title { color: var(--accent-2); }
.hr-title { color: var(--err); }
.badge-power { background: var(--accent-2); }
.badge-hr { background: var(--err); }
.device {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  padding: 14px 16px; border: 1px solid var(--border); border-radius: 14px; background: var(--bg-elev);
}
.device-info { display: flex; align-items: center; gap: 12px; min-width: 0; }
.device-radio { width: 12px; height: 12px; border-radius: 50%; border: 2px solid var(--muted); flex-shrink: 0; }
.device.connected .device-radio { border-color: var(--ok); background: var(--ok); box-shadow: 0 0 10px var(--ok); }
.device-meta { min-width: 0; }
.device-name { font-weight: 700; font-size: 15px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.device-addr { font-size: 12px; color: var(--muted); }
.device-state { font-size: 12px; font-weight: 600; color: var(--muted); margin-top: 2px; }
.device.connected .device-state { color: var(--ok); }
.device-actions { display: flex; gap: 8px; flex-shrink: 0; }
.badge { display: inline-block; font-size: 10px; font-weight: 700; letter-spacing: .5px; padding: 2px 7px; border-radius: 6px; background: var(--accent); color: #fff; vertical-align: middle; }

/* OTA */
.ota-progress { height: 8px; border-radius: 999px; background: var(--border); overflow: hidden; margin: 14px 0; }
.ota-bar { height: 100%; width: 0%; background: linear-gradient(90deg, var(--accent), var(--accent-2)); transition: width .2s; }
input[type="file"] { width: 100%; font-size: 13px; color: var(--muted); }
.ota-status { margin-top: 12px; font-size: 14px; font-weight: 600; }
.ota-status.ok { color: var(--ok); }
.ota-status.err { color: var(--err); }

/* Zone editor */
.zone-editor { display: flex; flex-direction: column; gap: 12px; margin: 8px 0 16px; }
.zone-item {
  display: grid; grid-template-columns: 46px 1fr 90px 90px 46px; gap: 10px; align-items: center;
  padding: 12px; border: 1px solid var(--border); border-radius: 14px; background: var(--bg-elev);
}
.zone-color { width: 46px; height: 46px; border-radius: 10px; border: none; cursor: pointer; padding: 0; background: none; }
.zone-item input[type="text"], .zone-item input[type="number"] { padding: 9px 10px; font-size: 14px; }
.zone-swatch { width: 46px; height: 46px; border-radius: 10px; }
.zone-item .zlabel { font-size: 11px; color: var(--muted); }
/* HR zone rows carry an extra column: % of Max HR + bpm range */
.zone-item.hr-zone-item { grid-template-columns: 46px 1fr 90px 90px 46px 120px; }
.zpct { display: flex; flex-direction: column; gap: 2px; align-self: center; text-align: center; }
.zpct b { font-size: 13px; font-weight: 700; }
.zpct span { font-size: 11px; color: var(--muted); }

/* Toast */
.toast {
  position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%) translateY(20px);
  background: var(--text); color: var(--bg); padding: 13px 22px; border-radius: 12px;
  font-weight: 600; font-size: 14px; opacity: 0; pointer-events: none; transition: all .3s; z-index: 50;
}
.toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }

/* Global banners */
.conn-banner, .demo-banner {
  position: fixed; top: 14px; left: 50%; transform: translateX(-50%);
  z-index: 40; display: flex; align-items: center; gap: 10px;
  padding: 10px 18px; border-radius: 12px; font-weight: 600; font-size: 14px;
}
.conn-banner {
  background: var(--bg-elev); border: 1px solid var(--err); color: var(--text);
  box-shadow: 0 6px 24px rgba(0,0,0,.35);
}
.demo-banner {
  background: var(--bg-elev); border: 1px solid var(--accent-2); color: var(--text);
  box-shadow: 0 6px 24px rgba(0,0,0,.35);
}
.demo-banner .pill-dot { background: var(--accent-2); box-shadow: 0 0 10px var(--accent-2); }
/* Same class-vs-[hidden] conflict as .onboarding: the display:flex above
   overrides the browser's [hidden] handling, so Stop test / natural
   completion (demoBanner.hidden = true) never visually hides the banner. */
.demo-banner[hidden] { display: none; }
/* Same class-vs-[hidden] conflict: the shared display:flex rule above
   overrides [hidden], so showHubBanner(false) on a connected WebSocket
   never visually hides the reconnect banner. */
.conn-banner[hidden] { display: none; }
.btn.small { padding: 7px 12px; font-size: 12px; }
.demo-btn { margin-top: 14px; }

/* About / Diagnostics */
.about-rows { display: flex; flex-direction: column; gap: 2px; margin: 10px 0; }
.about-rows > div {
  display: flex; justify-content: space-between; align-items: baseline; gap: 14px;
  padding: 9px 2px; border-bottom: 1px solid var(--border);
}
.about-rows span { color: var(--muted); font-size: 13px; }
.about-rows b { font-size: 14px; text-align: right; word-break: break-word; }
.export-out {
  width: 100%; min-height: 130px; margin-top: 12px; padding: 10px;
  border-radius: 10px; border: 1px solid var(--border); background: var(--bg-elev);
  color: var(--muted); font-family: ui-monospace, monospace; font-size: 11px; resize: vertical;
}

/* Onboarding overlay */
.onboarding {
  position: fixed; inset: 0; z-index: 60; display: flex; align-items: center; justify-content: center;
  background: rgba(8, 10, 16, .78); backdrop-filter: blur(6px); padding: 18px;
}
/* [hidden] must win over the display:flex above (class rules beat the UA
   [hidden]{display:none} default), or the overlay ignores hidden=true. */
.onboarding[hidden] { display: none; }
.ob-card {
  position: relative; width: 100%; max-width: 470px; padding: 28px;
  background: var(--bg-card, var(--bg-elev)); border: 1px solid var(--border); border-radius: 18px;
  display: flex; flex-direction: column; gap: 8px;
}
.ob-skip-btn {
  position: absolute; top: 14px; right: 16px; background: none; border: none; cursor: pointer;
  color: var(--muted); font-size: 12px; font-weight: 600; padding: 6px;
}
.ob-skip-btn:hover { color: var(--text); }
.ob-dot {
  width: 18px; height: 18px; border-radius: 50%;
  background: radial-gradient(circle at 35% 35%, var(--accent-2), var(--accent));
  box-shadow: 0 0 18px var(--accent);
  animation: ob-pulse 2.2s ease-in-out infinite;
}
@keyframes ob-pulse {
  0%, 100% { transform: scale(1); opacity: 1; }
  50% { transform: scale(1.25); opacity: .75; }
}
.ob-card h2 { margin: 6px 0 0; font-size: 22px; }
.ob-text { color: var(--muted); font-size: 14px; line-height: 1.55; margin: 0; }
.ob-info { color: var(--muted); font-size: 13px; padding: 10px 12px; border: 1px dashed var(--border); border-radius: 10px; }
.ob-body { display: flex; flex-direction: column; gap: 10px; }
.ob-devices { display: flex; flex-direction: column; gap: 8px; max-height: 190px; overflow-y: auto; }
.ob-dev-row {
  display: flex; align-items: center; justify-content: space-between; gap: 10px;
  padding: 10px 12px; border: 1px solid var(--border); border-radius: 10px; font-size: 14px;
}
.ob-dev-row small { color: var(--muted); font-size: 11px; }
.ob-dev-row em { color: var(--ok); font-style: normal; font-size: 12px; font-weight: 600; }
.ob-dev-row.connected { border-color: var(--ok); }
.ob-dev-row .btn { padding: 7px 14px; font-size: 12px; }
.ob-seg button { flex: 1; }
.ob-zone-cfg { display: flex; gap: 10px; }
.ob-field { flex: 1; display: flex; flex-direction: column; gap: 6px; font-size: 12px; font-weight: 600; color: var(--muted); }
.ob-field input {
  width: 100%; box-sizing: border-box; background: var(--bg-elev);
  border: 1px solid var(--border); border-radius: 10px; color: var(--text);
  font-size: 15px; padding: 9px 12px;
}
.ob-actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 6px; }

@media (max-width: 640px) {
  .grid { grid-template-columns: 1fr; }
  .power-value { font-size: 66px; }
  .zone-item { grid-template-columns: 40px 1fr 70px; grid-auto-rows: auto; }
  .zone-item .zmax { display: none; }
  .zone-item .zpct { display: none; }
  .field-row { flex-direction: column; gap: 0; }
  .ob-card { padding: 20px; }
  .ob-zone-cfg { flex-direction: column; }
  .about-rows b { font-size: 13px; }
})rgbwatt";

const char APP_JS[] = R"rgbwatt(
// ESP32 RGB Watt Zone Controller - Web UI
"use strict";

const $ = (id) => document.getElementById(id);
let config = null;
let ws = null;

const UI_VERSION = "1.2.0";   // Hub web UI version (About/Diagnostics)
let lastTel = null;           // last telemetry frame (Diagnostics)
let activeView = "dashboard"; // current nav view
let hubInfo = null;           // /api/info cache (About/Diagnostics)

function isHrMode() { return !!(config && config.controlSource === "hr"); }

// ---------------- Theme ----------------
function applyTheme(theme) {
  let effective = theme;
  if (theme === "system") {
    effective = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  }
  document.documentElement.setAttribute("data-theme", effective);
  document.querySelectorAll("#themeSwitch button").forEach((b) => {
    b.classList.toggle("active", b.dataset.themeVal === theme);
  });
}
function initTheme() {
  const saved = localStorage.getItem("theme") || "system";
  applyTheme(saved);
  document.querySelectorAll("#themeSwitch button").forEach((b) => {
    b.addEventListener("click", () => {
      const t = b.dataset.themeVal;
      localStorage.setItem("theme", t);
      applyTheme(t);
      if (config) { config.theme = t; postConfig({ theme: t }); }
    });
  });
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", () => {
    if ((localStorage.getItem("theme") || "system") === "system") applyTheme("system");
  });
}

// ---------------- Toast ----------------
let toastTimer = null;
function toast(msg) {
  const t = $("toast");
  t.textContent = msg;
  t.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => t.classList.remove("show"), 2200);
}

// ---------------- Nav ----------------
function initNav() {
  document.querySelectorAll(".nav-btn").forEach((b) => {
    b.addEventListener("click", () => {
      document.querySelectorAll(".nav-btn").forEach((x) => x.classList.remove("active"));
      document.querySelectorAll(".view").forEach((v) => v.classList.remove("active"));
      b.classList.add("active");
      $("view-" + b.dataset.view).classList.add("active");
      activeView = b.dataset.view;
      if (activeView === "devices") refreshDevices();
      if (activeView === "about") refreshAbout();
    });
  });
}

// ---------------- API ----------------
async function getConfig() {
  const r = await fetch("/api/config");
  config = await r.json();
  return config;
}
async function postConfig(patch) {
  const r = await fetch("/api/config", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  config = await r.json();
  return config;
}

// ---------------- Control source (Settings) ----------------
function initSourceSeg() {
  document.querySelectorAll("#sourceSeg button").forEach((b) => {
    b.addEventListener("click", async () => {
      if (b.classList.contains("active")) return;
      await postConfig({ controlSource: b.dataset.src });
      // The device disconnected the previous sensor and cleared its state.
      fillForms();
      toast(isHrMode() ? "Switched to Heart Rate mode" : "Switched to Power mode");
    });
  });
}

// ---------------- Populate forms ----------------
function fillForms() {
  $("ftpInput").value = config.ftp;
  $("zoneCountSel").value = config.zoneCount;
  $("smoothInput").value = config.smoothing;
  $("smoothVal").textContent = config.smoothing;
  $("timeoutInput").value = config.powerTimeout;
  $("hysInput").value = config.hysteresis;
  $("ledPinInput").value = config.ledPin;
  $("ledCountInput").value = config.ledCount;
  $("ledTypeSel").value = config.ledType;
  $("ledEffectSel").value = config.ledEffect;
  $("brightInput").value = config.brightness;
  $("brightVal").textContent = config.brightness + "%";
  $("autoReconnect").checked = config.autoReconnect;
  $("debugToggle").checked = config.debug;
  $("wifiSsid").value = config.wifiSsid || "";
  if (config.hrMax) $("hrMaxInput").value = config.hrMax;

  // ---- Dashboard adapts to the active control source ----
  const hr = isHrMode();
  $("powerUnit").textContent = hr ? "BPM" : "W";
  $("statFtpLabel").textContent = hr ? "Max HR" : "FTP";
  $("statFtp").textContent = hr ? config.hrMax : config.ftp;
  $("statFtpUnit").textContent = hr ? "BPM" : "W";
  $("statZones").textContent = hr ? (config.hrZones ? config.hrZones.length : 5) : config.zoneCount;
  $("hysUnit").textContent = hr ? "BPM" : "W";
  $("sourceMiniLabel").textContent = hr ? "Heart Rate" : "Power Source";
  document.querySelectorAll("#sourceSeg button").forEach((b) => {
    b.classList.toggle("active", (b.dataset.src === "hr") === hr);
  });

  // ---- Devices page: per-type saved source hints ----
  $("powerSavedHint").textContent = config.sourceName ? "Saved: " + config.sourceName : "No saved device";
  $("hrSavedHint").textContent = config.hrSourceName ? "Saved: " + config.hrSourceName : "No saved device";

  // ---- Zones page section subtitles ----
  $("powerZoneSub").textContent = "FTP: " + config.ftp + " W · " + config.zoneCount + " zones";
  // ---- HR zones: header summary + how Max HR interacts with the boundaries ----
  const hrSummary = "Max HR: " + (config.hrMax || 190) + " BPM · " +
    (config.hrZones ? config.hrZones.length : 5) + " zones. ";
  $("hrZoneNote").textContent = hrSummary + (config.hrZonesCustom
    ? "Boundaries customised — changing Max HR keeps them. Reset restores the defaults."
    : "Changing Max HR recalculates them automatically.");

  renderZoneEditor();
  renderHrZoneEditor();
}

// ---------------- Power zone editor ----------------
function renderZoneEditor() {
  const el = $("zoneEditor");
  el.innerHTML = "";
  if (!config.zones) return;
  config.zones.forEach((z, i) => {
    const hasMax = i < config.zones.length - 1;
    el.appendChild(zoneRow(z, i, "zone", { unit: "W", max: hasMax && z.max >= 0 ? z.max : null }));
  });
  bindZoneEditor(el, config.zones);
}

// ---------------- HR zone editor ----------------
function renderHrZoneEditor() {
  const el = $("hrEditor");
  el.innerHTML = "";
  if (!config.hrZones) return;
  const hrMax = config.hrMax || 190;
  config.hrZones.forEach((z, i) => {
    const isLast = i === config.hrZones.length - 1;
    // Z5 ends at Max HR; the server also reports max = hrMax for the last zone.
    const maxBpm = isLast || z.max < 0 ? hrMax : z.max;
    const pctLo = Math.floor(z.min / hrMax * 100);
    const pctHi = Math.round(maxBpm / hrMax * 100);
    el.appendChild(zoneRow(z, i, "hr-zone", {
      unit: "BPM", max: maxBpm, pct: pctLo + "–" + pctHi + "% Max HR",
    }));
  });
  bindZoneEditor(el, config.hrZones);
}

function zoneRow(z, i, testPrefix, opts) {
  const row = document.createElement("div");
  row.className = "zone-item" + (opts.pct ? " hr-zone-item" : "");
  const maxLabel = opts.max === null ? "∞" : opts.max;
  let html =
    '<input type="color" class="zone-color" value="' + z.color + '" data-i="' + i + '" data-testid="' + testPrefix + '-color-' + i + '" />' +
    '<div><div class="zlabel">Zone ' + (i + 1) + ' name</div>' +
      '<input type="text" class="zone-name" value="' + escapeAttr(z.name) + '" data-i="' + i + '" data-testid="' + testPrefix + '-name-' + i + '" /></div>' +
    '<div><div class="zlabel">Min ' + opts.unit + '</div>' +
      '<input type="number" class="zone-min" value="' + z.min + '" data-i="' + i + '" data-testid="' + testPrefix + '-min-' + i + '" /></div>' +
    '<div class="zmax"><div class="zlabel">Max ' + opts.unit + '</div>' +
      '<input type="number" value="' + (opts.max === null ? "" : opts.max) + '" disabled placeholder="' + maxLabel + '" /></div>' +
    '<div class="zone-swatch" style="background:' + z.color + '"></div>';
  if (opts.pct) {
    html += '<div class="zpct"><b>' + opts.pct + '</b><span>' + z.min + "–" + maxLabel + " " + opts.unit + '</span></div>';
  }
  row.innerHTML = html;
  return row;
}

function bindZoneEditor(el, zones) {
  el.querySelectorAll(".zone-color").forEach((c) =>
    c.addEventListener("input", (e) => {
      const i = +e.target.dataset.i;
      e.target.parentElement.querySelector(".zone-swatch").style.background = e.target.value;
      zones[i].color = e.target.value;
    })
  );
}
function escapeAttr(s) { return (s || "").replace(/"/g, "&quot;"); }

async function saveZones() {
  const zones = config.zones.map((z, i) => ({
    name: $("zoneEditor").querySelectorAll(".zone-name")[i].value,
    min: +$("zoneEditor").querySelectorAll(".zone-min")[i].value,
    color: $("zoneEditor").querySelectorAll(".zone-color")[i].value,
  }));
  await postConfig({ ftp: +$("ftpInput").value, zones: zones });
  fillForms();
  toast("Power zones saved");
}

async function saveHrZones() {
  const zones = config.hrZones.map((z, i) => ({
    name: $("hrEditor").querySelectorAll(".zone-name")[i].value,
    min: +$("hrEditor").querySelectorAll(".zone-min")[i].value,
    color: $("hrEditor").querySelectorAll(".zone-color")[i].value,
  }));
  await postConfig({ hrZones: zones });
  fillForms();
  toast("Heart Rate zones saved");
}

async function onZoneCountChange() {
  await postConfig({ zoneCount: +$("zoneCountSel").value, ftp: +$("ftpInput").value });
  fillForms();
  toast("Zone model updated");
}
async function resetZones() {
  await postConfig({ zoneCount: +$("zoneCountSel").value, ftp: +$("ftpInput").value });
  fillForms();
  toast("Zones reset to FTP defaults");
}
async function resetHrZones() {
  await postConfig({ hrZonesReset: true });
  fillForms();
  toast("Heart Rate zones reset to Max HR defaults");
}

// ---------------- Settings ----------------
async function saveSettings() {
  await postConfig({
    smoothing: +$("smoothInput").value,
    powerTimeout: +$("timeoutInput").value,
    hysteresis: +$("hysInput").value,
    ledPin: +$("ledPinInput").value,
    ledCount: +$("ledCountInput").value,
    ledType: $("ledTypeSel").value,
    ledEffect: +$("ledEffectSel").value,
    brightness: +$("brightInput").value,
    autoReconnect: $("autoReconnect").checked,
    debug: $("debugToggle").checked,
  });
  fillForms();
  toast("Settings saved");
}
async function saveWifi() {
  const ssid = $("wifiSsid").value.trim();
  if (!ssid) { toast("Enter an SSID"); return; }
  await fetch("/api/wifi", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ssid: ssid, pass: $("wifiPass").value }),
  });
  toast("Saved. Rebooting — reconnect to your network.");
}
async function factoryReset() {
  if (!confirm("Reset all settings to factory defaults?")) return;
  await fetch("/api/factory-reset", { method: "POST" });
  toast("Factory reset — rebooting…");
}

// ---------------- OTA ----------------
// A successful POST /api/ota only means the Hub ACCEPTED the file: it then
// flashes and reboots, briefly disappearing from the network. Success is
// reported only after the Hub answers /api/info again, and failure only if
// it does not come back within the polling budget - never from the POST
// alone, and never from the WebSocket disconnect the expected reboot
// causes (that is handled by the normal connection banner).
const OTA_POLL_MS = 2000;
const OTA_DROP_POLLS = 10;   // ~20 s waiting for the reboot gap
const OTA_BACK_POLLS = 45;    // ~90 s for flash + reboot + Wi-Fi rejoin
let otaBusy = false;

function setOtaStatus(msg, cls) {
  const el = $("otaStatus");
  if (!el) return;
  el.textContent = msg || "";
  el.className = "ota-status" + (cls ? " " + cls : "");
  el.hidden = !msg;
}
function otaSetBusy(busy) {
  otaBusy = busy;
  $("otaBtn").disabled = busy;
  $("otaFile").disabled = busy;
}
async function otaInfoReachable() {
  try { return (await fetch("/api/info", { cache: "no-store" })).ok; }
  catch (_) { return false; }
}
async function waitHubUnreachable() {
  // The old firmware answers /api/info right up to the reboot; wait for
  // that gap so a fast first poll cannot mistake the pre-reboot Hub for
  // the rebooted one.
  for (let i = 0; i < OTA_DROP_POLLS; i++) {
    if (!(await otaInfoReachable())) return true;
    await new Promise((r) => setTimeout(r, OTA_POLL_MS));
  }
  return false;   // no gap observed (very quick reboot) - keep waiting anyway
}
async function waitHubBack() {
  let announced = false;
  for (let i = 0; i < OTA_BACK_POLLS; i++) {
    if (await otaInfoReachable()) return true;
    if (!announced) { setOtaStatus("Reconnecting to Hub…"); announced = true; }
    await new Promise((r) => setTimeout(r, OTA_POLL_MS));
  }
  return false;
}
async function otaFinishUpdate() {
  const preInfo = hubInfo && hubInfo.deviceId ? hubInfo : null;
  setOtaStatus("Installing update…");
  await waitHubUnreachable();
  setOtaStatus("Hub restarting…");
  await new Promise((r) => setTimeout(r, OTA_POLL_MS));   // the reboot takes at least a beat
  const back = await waitHubBack();
  if (!back) {
    setOtaStatus("Update not confirmed — the Hub did not come back. Check its power and Wi-Fi, then reload this page.", "err");
    toast("Hub did not return after the update");
    otaSetBusy(false);
    return;
  }
  await loadHubInfo();   // refresh About/Diagnostics with the running firmware
  const info = hubInfo;
  let suffix = info && info.version ? " — running firmware " + info.version : "";
  if (preInfo && info && preInfo.deviceId !== info.deviceId) suffix += " (different Hub device ID)";
  $("otaBar").style.width = "100%";
  setOtaStatus("Update successful ✓" + suffix, "ok");
  toast("Update successful");
  otaSetBusy(false);
}
function otaUpload() {
  if (otaBusy) return;
  const f = $("otaFile").files[0];
  if (!f) { toast("Choose a firmware .bin first"); return; }
  loadHubInfo();   // record pre-update /api/info for comparison
  otaSetBusy(true);
  const bar = $("otaBar");
  bar.style.width = "0%";
  setOtaStatus("Uploading firmware…");
  const fd = new FormData();
  fd.append("firmware", f, f.name);
  const xhr = new XMLHttpRequest();
  xhr.open("POST", "/api/ota");
  xhr.upload.onprogress = (e) => {
    if (e.lengthComputable) bar.style.width = Math.round((e.loaded / e.total) * 100) + "%";
  };
  xhr.onload = () => {
    let ok = false;
    try { ok = JSON.parse(xhr.responseText).ok; } catch (_) {}
    if (ok) otaFinishUpdate();   // accepted -> follow the reboot + reconnect
    else {
      setOtaStatus("Update failed — the Hub rejected the file.", "err");
      toast("Update failed");
      otaSetBusy(false);
    }
  };
  xhr.onerror = () => {
    setOtaStatus("Upload error — could not send the file to the Hub.", "err");
    toast("Upload error");
    otaSetBusy(false);
  };
  xhr.send(fd);
}

// ---------------- Devices (Power + Heart Rate sensors) ----------------
const TYPE_LABEL = { CPS: "Power Meter", FTMS: "Smart Trainer", HRS: "Heart Rate Monitor" };
let deviceTimer = null;
async function scan() {
  await fetch("/api/scan", { method: "POST" });
  $("scanBtn").textContent = "Searching…";
  $("scanBtn").disabled = true;
  toast("Searching for power and heart rate sensors…");
  let ticks = 0;
  clearInterval(deviceTimer);
  deviceTimer = setInterval(async () => {
    await refreshDevices();
    if (++ticks > 8) {
      clearInterval(deviceTimer);
      $("scanBtn").textContent = "Scan";
      $("scanBtn").disabled = false;
    }
  }, 1000);
}
async function refreshDevices() {
  const r = await fetch("/api/devices");
  const data = await r.json();
  const all = data.devices || [];
  renderDeviceList($("powerDeviceList"), all.filter((d) => d.category === "power"), data.scanning);
  renderDeviceList($("hrDeviceList"), all.filter((d) => d.category === "hr"), data.scanning);
}
function renderDeviceList(list, devices, scanning) {
  if (!devices.length) {
    list.innerHTML = '<div class="empty">' + (scanning ? "Searching…" : "No devices found. Tap Scan.") + "</div>";
    return;
  }
  list.innerHTML = "";
  devices.forEach((d) => {
    const row = document.createElement("div");
    row.className = "device" + (d.connected ? " connected" : "");
    row.innerHTML =
      '<div class="device-info">' +
        '<span class="device-radio"></span>' +
        '<div class="device-meta">' +
          '<div class="device-name">' + escapeHtml(d.name) +
            ' <span class="badge badge-' + d.category + '">' + (TYPE_LABEL[d.type] || d.type) + '</span></div>' +
          '<div class="device-addr">' + d.address + "  ·  " + d.rssi + " dBm</div>" +
          '<div class="device-state">' + (d.connected ? "Connected" : "Available") + "</div>" +
        "</div></div>" +
      '<div class="device-actions"></div>';
    const actions = row.querySelector(".device-actions");
    if (d.connected) {
      actions.appendChild(mkBtn("Disconnect", "", () => disconnect()));
      actions.appendChild(mkBtn("Forget", "danger", () => forget()));
    } else {
      actions.appendChild(mkBtn("Connect", "primary", () => connect(d)));
    }
    list.appendChild(row);
  });
}
function mkBtn(label, cls, fn) {
  const b = document.createElement("button");
  b.className = "btn " + cls;
  b.textContent = label;
  b.setAttribute("data-testid", "device-" + label.toLowerCase() + "-btn");
  b.addEventListener("click", fn);
  return b;
}
async function connect(d) {
  // Connecting activates the device's control source first (mutual exclusion):
  // the previously active sensor is disconnected on the device side.
  const switching = (d.category === "hr") !== isHrMode();
  await fetch("/api/connect", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ address: d.address, name: d.name, category: d.category }),
  });
  await getConfig();   // pick up the (possibly switched) control source immediately
  fillForms();
  toast(switching
    ? "Switching to " + (d.category === "hr" ? "Heart Rate" : "Power") + " mode — connecting to " + d.name + "…"
    : "Connecting to " + d.name + "…");
  setTimeout(refreshDevices, 1200);
}
async function disconnect() { await fetch("/api/disconnect", { method: "POST" }); toast("Disconnected"); setTimeout(refreshDevices, 600); }
async function forget() { await fetch("/api/forget", { method: "POST" }); toast("Source forgotten"); setTimeout(refreshDevices, 600); }
function escapeHtml(s) { const d = document.createElement("div"); d.textContent = s; return d.innerHTML; }

// ---------------- WebSocket telemetry ----------------
// The Hub broadcasts telemetry ~5x/s, so sustained silence means the socket
// is dead. In the Android WebView (mobile shell iframe) a dead WebSocket can
// drop WITHOUT ever firing onclose - the network path (emulator NAT, Wi-Fi
// power-save) silently blackholes it. The dashboard would then freeze on the
// last received frame forever while REST commands still work. A watchdog
// re-arms on every telemetry frame and force-closes a silent socket, letting
// the normal onclose reconnect take over.
const WS_SILENCE_MS = 6000;   // ~30 missed telemetry frames = definitively dead
let wsWatchdog = null;
function armWsWatchdog() {
  clearTimeout(wsWatchdog);
  wsWatchdog = setTimeout(() => { try { ws.close(); } catch (_) {} }, WS_SILENCE_MS);
}
function initWs() {
  const proto = location.protocol === "https:" ? "wss" : "ws";
  ws = new WebSocket(proto + "://" + location.host + "/ws");
  ws.onmessage = (e) => { armWsWatchdog(); showHubBanner(false); try { updateLive(JSON.parse(e.data)); } catch (_) {} };
  ws.onerror = () => { try { ws.close(); } catch (_) {} };
  ws.onclose = () => { clearTimeout(wsWatchdog); showHubBanner(true); setTimeout(initWs, 2000); };
  armWsWatchdog();   // a socket that never opens at all must not hang either
}
const STATE_MAP = {
  RECEIVING_POWER: { cls: "live", label: "Receiving Data" },
  CONNECTED: { cls: "ok", label: "Connected" },
  CONNECTING: { cls: "warn", label: "Connecting…" },
  RECONNECTING: { cls: "warn", label: "Reconnecting…" },
  SCANNING: { cls: "warn", label: "Searching…" },
  DISCONNECTED: { cls: "", label: "Disconnected" },
  STARTING: { cls: "", label: "Starting" },
  ERROR: { cls: "err", label: "Error" },
};
function updateLive(t) {
  // Another client (or the Devices page) may have switched the control
  // source: follow immediately so units and zone colours match the mode.
  const tMode = t.mode || (config && config.controlSource);
  if (config && tMode && config.controlSource !== tMode) {
    config.controlSource = tMode;
    fillForms();
  }
  const hr = isHrMode();
  // Plain-English states instead of developer shorthand.
  let stateLabel = (t.state === "RECEIVING_POWER")
    ? (hr ? "Receiving heart rate" : "Receiving power")   // mode-specific wording
    : (STATE_MAP[t.state] || STATE_MAP.STARTING).label;
  if (t.state === "DISCONNECTED") {
    stateLabel = hr ? "No heart rate sensor connected" : "No power sensor connected";
  }
  $("powerWatts").textContent = t.smoothed;
  $("zoneNum").textContent = "Z" + (t.zone + 1);
  $("zoneName").textContent = (t.zoneName || "—").replace(/^Z\d+\s·\s/, "");
  const s = STATE_MAP[t.state] || STATE_MAP.STARTING;
  const pill = $("statusPill");
  pill.className = "status-pill " + s.cls;
  $("statusText").textContent = t.sim ? "Lighting test" : stateLabel;
  lastTel = t;
  if (activeView === "about") fillAbout();

  // Colour glow + brand: must show the SAME zone as the label. Use the current
  // zone's configured colour of the ACTIVE control source so
  // zone number = zone name = displayed colour.
  const zones = hr ? (config.hrZones || []) : (config.zones || []);
  const zoneColor = (t.zone >= 0 && t.zone < zones.length) ? zones[t.zone].color : t.color;
  $("powerGlow").style.background = "radial-gradient(circle, " + zoneColor + "cc, transparent 70%)";
  $("brandDot").style.background = zoneColor;
  $("brandDot").style.boxShadow = "0 0 24px " + zoneColor + "88";

  // Dashboard source
  $("dashSourceName").textContent = t.source || (t.sim ? "Simulation" : "—");
  const ds = $("dashSourceState");
  ds.querySelector("span:last-child").textContent = t.sim ? "Lighting test" : stateLabel;
  ds.querySelector(".pill-dot").style.background = s.cls === "live" || s.cls === "ok" ? "var(--ok)" : "var(--muted)";
}

// ---------------- Hub connection banner ----------------
function showHubBanner(show) {
  const b = $("hubBanner");
  if (b) b.hidden = !show;
}

// ---------------- First-run onboarding ----------------
// Hardware setup wizard (setup, NOT workout onboarding):
// Welcome -> Hub -> Add Sensor -> Control Source -> Zones -> Test Lighting -> Setup Complete.
// Skippable at any time; completion persists in localStorage; re-runnable from
// About. Uses only existing APIs (scan / connect / config / simulation).
const ONBOARD_KEY = "zoneglow.onboarding.done";
let obState = null;   // { step }
let obPoll = null;    // wizard scan poller

function onboardingDone() {
  try { return localStorage.getItem(ONBOARD_KEY) === "1"; } catch (_) { return false; }
}
function markOnboardingDone() {
  try { localStorage.setItem(ONBOARD_KEY, "1"); } catch (_) {}
}
function startOnboarding(force) {
  if (!force && (onboardingDone() || obState)) return;
  obState = { step: 0 };
  $("onboarding").hidden = false;
  renderOnboarding();
}
function closeOnboarding(done) {
  if (obPoll) { clearInterval(obPoll); obPoll = null; }
  obState = null;
  $("onboarding").hidden = true;
  if (done) { markOnboardingDone(); toast("Setup complete"); }
}
function obAddBtn(label, cls, fn, parent) {
  const b = document.createElement("button");
  b.className = "btn " + (cls || "");
  b.textContent = label;
  b.addEventListener("click", fn);
  parent.appendChild(b);
  return b;
}
function renderOnboarding() {
  const s = obState.step;
  const body = $("obBody"); body.innerHTML = "";
  const actions = $("obActions"); actions.innerHTML = "";
  const next = () => { obState.step = s + 1; renderOnboarding(); };
  const back = () => { obState.step = Math.max(0, s - 1); renderOnboarding(); };

  if (s === 0) {
    $("obTitle").textContent = "Welcome to ZoneGlow";
    $("obText").textContent = "Set up your Hub and its zone lighting in a few short steps. You can skip anytime — everything stays available in the app.";
    obAddBtn("Get started", "primary", next, actions);
  } else if (s === 1) {
    $("obTitle").textContent = "Your Hub";
    $("obText").textContent = "This app talks to the ZoneGlow Hub over Wi-Fi.";
    const info = document.createElement("div");
    info.className = "ob-info";
    info.textContent = "Device ID: " + ((hubInfo && hubInfo.deviceId) || "unknown") +
      "  ·  Firmware: " + ((hubInfo && hubInfo.version) || "unknown");
    body.appendChild(info);
    obAddBtn("Back", "", back, actions);
    obAddBtn("Next", "primary", next, actions);
  } else if (s === 2) {
    $("obTitle").textContent = "Add a sensor";
    $("obText").textContent = "Scan for power meters and heart rate monitors near the Hub, then connect one. You can also do this later on the Devices page.";
    const list = document.createElement("div");
    list.id = "obDeviceList";
    list.className = "ob-devices";
    body.appendChild(list);
    obRenderDevices([]);
    obAddBtn("Scan", "primary", obScan, body);
    obAddBtn("Back", "", back, actions);
    obAddBtn("Next", "primary", next, actions);
  } else if (s === 3) {
    $("obTitle").textContent = "Select control source";
    $("obText").textContent = "Choose what drives your lights: power or heart rate. Connecting the other sensor type later switches this automatically.";
    const seg = document.createElement("div");
    seg.className = "seg ob-seg";
    ["power", "hr"].forEach((src) => {
      const b = document.createElement("button");
      b.dataset.src = src;
      b.textContent = src === "hr" ? "Heart Rate" : "Power";
      b.classList.toggle("active", (src === "hr") === isHrMode());
      b.addEventListener("click", async () => {
        await postConfig({ controlSource: src });
        fillForms();
        seg.querySelectorAll("button").forEach((x) => x.classList.toggle("active", x === b));
      });
      seg.appendChild(b);
    });
    body.appendChild(seg);
    obAddBtn("Back", "", back, actions);
    obAddBtn("Next", "primary", next, actions);
  } else if (s === 4) {
    // Zone basics: quick FTP / Max HR fields (the values the zone boundaries
    // are generated from). Full name/color editing stays on the Zones page.
    $("obTitle").textContent = "Configure zones";
    $("obText").textContent = "Zone boundaries are generated from your FTP (power) and Max HR (heart rate). Adjust them now, or fine-tune names, boundaries and colors later on the Zones page.";
    const wrap = document.createElement("div");
    wrap.className = "ob-zone-cfg";
    const addField = (label, key) => {
      const f = document.createElement("label");
      f.className = "ob-field";
      const l = document.createElement("span");
      l.textContent = label;
      const inp = document.createElement("input");
      inp.type = "number";
      inp.value = config[key];
      inp.addEventListener("change", async () => {
        const patch = {};
        patch[key] = +inp.value;
        await postConfig(patch);
        fillForms();
        toast(label + " updated");
      });
      f.appendChild(l);
      f.appendChild(inp);
      wrap.appendChild(f);
    };
    addField("FTP (W)", "ftp");
    addField("Max HR (BPM)", "hrMax");
    body.appendChild(wrap);
    obAddBtn("Back", "", back, actions);
    obAddBtn("Next", "primary", next, actions);
  } else if (s === 5) {
    $("obTitle").textContent = "Test lighting";
    $("obText").textContent = "Run a quick test that cycles through every zone so you can verify the colors on your LED strip. It never changes your settings.";
    obAddBtn("Test all zones", "primary", () => startDemo(1), body);
    obAddBtn("Back", "", back, actions);
    obAddBtn("Next", "primary", next, actions);
  } else if (s === 6) {
    // Hardware-setup ending: the Hub is standalone and keeps running with the
    // app closed - clients are configurators, not the controller.
    $("obTitle").textContent = "Setup complete";
    $("obText").textContent = "Your Hub is configured and runs on its own — you can close this app any time. Reconnect later to adjust settings or check status.";
    obAddBtn("Done", "primary", () => closeOnboarding(true), actions);
  }
}
async function obScan() {
  try { await fetch("/api/scan", { method: "POST" }); }
  catch (_) { toast("Cannot reach the Hub"); return; }
  toast("Searching for sensors…");
  let ticks = 0;
  if (obPoll) clearInterval(obPoll);
  obPoll = setInterval(async () => {
    try {
      const r = await fetch("/api/devices");
      obRenderDevices((await r.json()).devices || []);
    } catch (_) {}
    if (++ticks > 9 && obPoll) { clearInterval(obPoll); obPoll = null; }
  }, 1000);
}
function obRenderDevices(devices) {
  const list = $("obDeviceList");
  if (!list) return;
  if (!devices.length) {
    list.innerHTML = '<div class="empty">No sensors found yet. Tap Scan.</div>';
    return;
  }
  list.innerHTML = "";
  devices.slice(0, 6).forEach((d) => {
    const row = document.createElement("div");
    row.className = "ob-dev-row" + (d.connected ? " connected" : "");
    const label = document.createElement("span");
    label.innerHTML = escapeHtml(d.name) +
      ' <small>(' + (d.category === "hr" ? "Heart Rate" : "Power") + ")</small>";
    row.appendChild(label);
    if (d.connected) {
      const ok = document.createElement("em");
      ok.textContent = "Connected";
      row.appendChild(ok);
    } else {
      obAddBtn("Connect", "primary", () => connect(d), row);
    }
    list.appendChild(row);
  });
}

// ---------------- Lighting Test (user-facing "Test Lighting") ----------------
// A hardware verification sweep driven through the EXISTING /api/simulation
// endpoint: cycles Z1..Zmax and back down so the user can check every zone's
// color on the strip. It is a lighting test tool, NOT a simulated workout;
// stopping it returns control to the real sensor untouched. The developer
// Simulation Mode (PC simulator /dev panel) remains separate.
const DEMO_STEP_MS = 1200;
let demoTimer = null;
let demoPos = 0;
let demoCyclesLeft = 0;

async function postSimulation(patch, opts) {
  return fetch("/api/simulation", Object.assign({
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  }, opts || {}));
}
function demoSequence() {
  // One value per zone: a little above each zone's lower bound, so the cycle
  // walks Z1 -> Z2 -> ... -> Zmax and then back down (Zmax-1 ... Z1).
  const zones = isHrMode() ? (config.hrZones || []) : (config.zones || []);
  const vals = zones.map((z) => (z.min || 0) + (isHrMode() ? 3 : 10));
  if (!vals.length) return [];
  return vals.concat(vals.slice(0, -1).reverse());
}
async function startDemo(cycles) {
  if (demoTimer || !config) return;   // already running
  demoPos = 0;
  demoCyclesLeft = cycles || 1;   // dashboard runs exactly ONE automatic cycle, then stops
  try { await postSimulation({ enabled: true }); }
  catch (_) { toast("Cannot reach the Hub"); return; }
  $("demoBanner").hidden = false;
  await demoTick();
  demoTimer = setInterval(demoTick, DEMO_STEP_MS);
}
async function stopDemo() {
  if (demoTimer) { clearInterval(demoTimer); demoTimer = null; }
  $("demoBanner").hidden = true;
  try { await postSimulation({ enabled: false }); } catch (_) {}
}
async function demoTick() {
  const seq = demoSequence();
  if (!seq.length || demoPos >= seq.length * demoCyclesLeft) { await stopDemo(); return; }
  const v = seq[demoPos % seq.length];
  demoPos++;
  const patch = isHrMode() ? { bpm: v } : { watts: v };
  try { await postSimulation(patch); }
  catch (_) { await stopDemo(); toast("Connection to Hub lost — lighting test stopped"); }
}
// Best effort: never leave the Hub in Demo Mode when the UI goes away.
document.addEventListener("pagehide", () => {
  if (!demoTimer) return;
  try {
    if (typeof navigator !== "undefined" && navigator.sendBeacon) {
      navigator.sendBeacon("/api/simulation",
        new Blob([JSON.stringify({ enabled: false })], { type: "application/json" }));
    }
  } catch (_) {}
});

// ---------------- Configuration backup (export / import) ----------------
// Versioned JSON schema. Validation runs completely BEFORE anything is sent
// to the Hub, so a malformed file can never partially overwrite the config.
// Secrets (Wi-Fi) and sensor pairings are never exported.
const CFG_SCHEMA = "zoneglow.config";
const CFG_VERSION = 1;
const CFG_KEYS = ["controlSource", "ftp", "smoothing", "powerTimeout", "hysteresis",
  "zoneCount", "zones", "hrMax", "hrZonesCustom", "hrZones", "ledPin", "ledCount",
  "brightness", "ledType", "ledEffect", "autoReconnect", "debug", "theme"];

function buildBackup() {
  const cfg = {};
  CFG_KEYS.forEach((k) => { if (config && config[k] !== undefined) cfg[k] = config[k]; });
  return {
    schema: CFG_SCHEMA,
    version: CFG_VERSION,
    app: "ZoneGlow",
    exportedAt: new Date().toISOString(),
    config: cfg,
  };
}
function validateImportedConfig(doc) {
  try {
    if (!doc || typeof doc !== "object" || Array.isArray(doc)) {
      throw new Error("Not a valid configuration backup");
    }
    if (doc.schema !== CFG_SCHEMA) {
      throw new Error("This file is not a ZoneGlow configuration backup");
    }
    if (doc.version !== CFG_VERSION) {
      throw new Error("Unsupported backup version: " + doc.version);
    }
    const c = doc.config;
    if (!c || typeof c !== "object" || Array.isArray(c)) {
      throw new Error("Backup is missing its configuration data");
    }
    const int = (v, lo, hi) => {
      const n = Number(v);
      if (!Number.isInteger(n) || n < lo || n > hi) return null;
      return n;
    };
    const out = {};

    const controlSource = c.controlSource === "hr" || c.controlSource === "power"
      ? c.controlSource : null;
    if (!controlSource) throw new Error("Control source must be power or heart rate");
    out.controlSource = controlSource;

    const ftp = int(c.ftp, 50, 1000);
    if (ftp === null) throw new Error("FTP must be a whole number between 50 and 1000");
    out.ftp = ftp;

    const smoothing = int(c.smoothing, 0, 100);
    if (smoothing === null) throw new Error("Smoothing must be between 0 and 100");
    out.smoothing = smoothing;

    const powerTimeout = int(c.powerTimeout, 500, 60000);
    if (powerTimeout === null) throw new Error("Data timeout must be between 500 and 60000 ms");
    out.powerTimeout = powerTimeout;

    const hysteresis = int(c.hysteresis, 0, 100);
    if (hysteresis === null) throw new Error("Hysteresis must be between 0 and 100");
    out.hysteresis = hysteresis;

    const zoneCount = int(c.zoneCount, 5, 7);
    if (zoneCount === null) throw new Error("Zone count must be 5, 6 or 7");
    out.zoneCount = zoneCount;

    if (!Array.isArray(c.zones) || c.zones.length !== zoneCount) {
      throw new Error("Power zones (" + (c.zones ? c.zones.length : 0) +
        ") do not match the zone count (" + zoneCount + ")");
    }
    let prevMin = -1;
    out.zones = c.zones.map((z, i) => {
      if (!z || typeof z !== "object") throw new Error("Power zone " + (i + 1) + " is malformed");
      if (typeof z.name !== "string" || !z.name.trim()) {
        throw new Error("Power zone " + (i + 1) + " needs a name");
      }
      const min = int(z.min, 0, 9999);
      if (min === null) throw new Error("Power zone " + (i + 1) + " has an invalid minimum");
      if (min <= prevMin) throw new Error("Power zone minimums must increase from zone to zone");
      prevMin = min;
      if (!/^#[0-9a-fA-F]{6}$/.test(z.color || "")) {
        throw new Error("Power zone " + (i + 1) + " has an invalid color");
      }
      return { name: z.name.trim().slice(0, 23), min: min, color: z.color };
    });

    const hrMax = int(c.hrMax, 100, 230);
    if (hrMax === null) throw new Error("Max HR must be between 100 and 230");
    out.hrMax = hrMax;

    if (!Array.isArray(c.hrZones) || c.hrZones.length !== 5) {
      throw new Error("Heart Rate zones must contain exactly 5 zones");
    }
    let prevBpm = -1;
    out.hrZones = c.hrZones.map((z, i) => {
      if (!z || typeof z !== "object") throw new Error("Heart Rate zone " + (i + 1) + " is malformed");
      if (typeof z.name !== "string" || !z.name.trim()) {
        throw new Error("Heart Rate zone " + (i + 1) + " needs a name");
      }
      const min = int(z.min, 0, 250);
      if (min === null) throw new Error("Heart Rate zone " + (i + 1) + " has an invalid minimum");
      if (min <= prevBpm) throw new Error("Heart Rate zone minimums must increase from zone to zone");
      prevBpm = min;
      if (!/^#[0-9a-fA-F]{6}$/.test(z.color || "")) {
        throw new Error("Heart Rate zone " + (i + 1) + " has an invalid color");
      }
      return { name: z.name.trim().slice(0, 23), min: min, color: z.color };
    });
    if (c.hrZonesCustom !== undefined) {
      if (typeof c.hrZonesCustom !== "boolean") throw new Error("hrZonesCustom must be true or false");
      out.hrZonesCustom = c.hrZonesCustom;
    }

    const ledPin = int(c.ledPin, 0, 39);
    if (ledPin === null) throw new Error("LED GPIO pin must be between 0 and 39");
    out.ledPin = ledPin;
    const ledCount = int(c.ledCount, 1, 1000);
    if (ledCount === null) throw new Error("LED count must be between 1 and 1000");
    out.ledCount = ledCount;
    const brightness = int(c.brightness, 0, 100);
    if (brightness === null) throw new Error("Brightness must be between 0 and 100");
    out.brightness = brightness;
    if (c.ledType !== "WS2812B" && c.ledType !== "SK6812") {
      throw new Error("LED type must be WS2812B or SK6812");
    }
    out.ledType = c.ledType;
    const ledEffect = int(c.ledEffect, 0, 2);
    if (ledEffect === null) throw new Error("LED effect must be 0, 1 or 2");
    out.ledEffect = ledEffect;

    ["autoReconnect", "debug"].forEach((k) => {
      if (c[k] !== undefined) {
        if (typeof c[k] !== "boolean") throw new Error(k + " must be true or false");
        out[k] = c[k];
      }
    });
    if (c.theme !== undefined && c.theme !== null && c.theme !== "") {
      if (["light", "dark", "system"].indexOf(c.theme) === -1) {
        throw new Error("Theme must be light, dark or system");
      }
      out.theme = c.theme;
    }
    return { ok: true, config: out };
  } catch (e) {
    return { ok: false, error: e && e.message ? e.message : "Invalid backup" };
  }
}
function exportConfig() {
  const json = JSON.stringify(buildBackup(), null, 2);
  const out = $("exportOut");
  out.value = json;
  out.hidden = false;
  $("exportCopyBtn").hidden = false;
  try {
    // File download where the platform supports it; the copyable text field
    // stays visible as the fallback (e.g. Android WebView).
    const blob = new Blob([json], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "zoneglow-config-" + new Date().toISOString().slice(0, 10) + ".json";
    a.click();
    setTimeout(() => { try { URL.revokeObjectURL(a.href); } catch (_) {} }, 5000);
  } catch (_) {}
  toast("Configuration exported");
}
async function applyImportedConfig(doc) {
  const v = validateImportedConfig(doc);
  if (!v.ok) { toast(v.error); return false; }
  let ok = true;
  try { await postConfig(v.config); }   // one atomic request
  catch (_) { ok = false; }
  if (!ok) { toast("Could not reach the Hub — configuration unchanged"); return false; }
  fillForms();
  toast("Configuration restored");
  return true;
}
function importConfigFile(file) {
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    let doc = null;
    try { doc = JSON.parse(reader.result); } catch (_) {}
    if (doc === null) { toast("Not a valid backup file"); return; }
    applyImportedConfig(doc);   // validates fully BEFORE anything is applied
  };
  reader.readAsText(file);
}

// ---------------- About / Diagnostics ----------------
async function loadHubInfo() {
  try { const r = await fetch("/api/info"); hubInfo = await r.json(); }
  catch (_) { hubInfo = null; }
  return hubInfo;
}
function refreshAbout() {
  loadHubInfo().then(fillAbout, fillAbout);
}
function wsStatusText() {
  if (!ws) return "not started";
  if (ws.readyState === 1) return "connected";
  if (ws.readyState === 0) return "connecting";
  return "disconnected";
}
function fillAbout() {
  if (!$("aboutAppVersion")) return;
  $("aboutAppVersion").textContent = UI_VERSION;
  $("aboutFwVersion").textContent = hubInfo
    ? (hubInfo.version + (hubInfo.build ? " (" + hubInfo.build + ")" : ""))
    : "unavailable";
  $("aboutDeviceId").textContent = (hubInfo && hubInfo.deviceId) || "unavailable";
  const connected = wsStatusText() === "connected";
  $("diagWs").textContent = connected ? "connected" : "reconnecting…";
  $("diagWsState").textContent = wsStatusText();
  $("diagApi").textContent = hubInfo ? "reachable" : "unreachable";
  const hr = isHrMode();
  $("diagSource").textContent = hr ? "Heart Rate" : "Power";
  const sensor = (lastTel && lastTel.source) ||
    (config ? (hr ? config.hrSourceName : config.sourceName) : "");
  const state = lastTel ? lastTel.state.replace(/_/g, " ").toLowerCase() : "unknown";
  $("diagSensor").textContent = (sensor ? sensor + " — " : "") + state;
}
function buildDiagnosticsText() {
  const hr = isHrMode();
  return [
    "ZoneGlow diagnostics",
    "Generated: " + new Date().toISOString(),
    "App version: " + UI_VERSION,
    "Hub firmware: " + ((hubInfo && hubInfo.version) || "unknown") +
      ((hubInfo && hubInfo.build) ? " (" + hubInfo.build + ")" : ""),
    "Hub device ID: " + ((hubInfo && hubInfo.deviceId) || "unknown"),
    "Hub connection (WebSocket): " + wsStatusText(),
    "API (/api/info): " + (hubInfo ? "reachable" : "unreachable"),
    "Control source: " + (hr ? "Heart Rate" : "Power"),
    "Sensor: " + ((lastTel && lastTel.source) || "none"),
    "Sensor state: " + (lastTel ? lastTel.state : "unknown"),
    "Zone: " + (lastTel ? "Z" + (lastTel.zone + 1) : "-") +
      ((lastTel && lastTel.zoneName) ? " (" + lastTel.zoneName + ")" : ""),
    "FTP: " + (config ? config.ftp : "?") + " W",
    "Max HR: " + (config ? config.hrMax : "?") + " BPM",
    "LED: " + (config ? config.ledCount : "?") + "x " + (config ? config.ledType : "?") +
      ", brightness " + (config ? config.brightness : "?") + "%",
  ].join("\n");
}
async function copyText(text) {
  try {
    if (typeof navigator !== "undefined" && navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch (_) {}
  try {
    if (!document.body) return false;
    const ta = document.createElement("textarea");
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return !!ok;
  } catch (_) { return false; }
}
async function copyDiagnostics() {
  const ok = await copyText(buildDiagnosticsText());
  toast(ok ? "Diagnostics copied" : "Copy not available here");
}

// ---------------- Init ----------------
async function init() {
  initTheme();
  initNav();
  await getConfig();
  // Sync stored theme with device config (device is source of truth on first load if set)
  if (config.theme && !localStorage.getItem("theme")) { localStorage.setItem("theme", config.theme); applyTheme(config.theme); }
  fillForms();
  initWs();

  $("ftpInput").addEventListener("change", async () => { await postConfig({ ftp: +$("ftpInput").value }); fillForms(); toast("FTP updated"); });
  $("hrMaxInput").addEventListener("change", async () => { await postConfig({ hrMax: +$("hrMaxInput").value }); fillForms(); toast("Max HR updated"); });
  $("zoneCountSel").addEventListener("change", onZoneCountChange);
  $("saveZonesBtn").addEventListener("click", saveZones);
  $("saveHrZonesBtn").addEventListener("click", saveHrZones);
  $("resetZonesBtn").addEventListener("click", resetZones);
  $("resetHrZonesBtn").addEventListener("click", resetHrZones);
  $("saveSettingsBtn").addEventListener("click", saveSettings);
  $("wifiSaveBtn").addEventListener("click", saveWifi);
  $("factoryBtn").addEventListener("click", factoryReset);
  $("otaBtn").addEventListener("click", otaUpload);
  $("ledEffectSel").addEventListener("change", async () => { await postConfig({ ledEffect: +$("ledEffectSel").value }); toast("Effect updated"); });
  $("scanBtn").addEventListener("click", scan);
  $("smoothInput").addEventListener("input", () => ($("smoothVal").textContent = $("smoothInput").value));
  $("brightInput").addEventListener("input", () => ($("brightVal").textContent = $("brightInput").value + "%"));

  // ---- Demo Mode ----
  $("demoBtn").addEventListener("click", () => startDemo());
  $("demoExitBtn").addEventListener("click", stopDemo);

  // ---- About / Diagnostics ----
  $("copyDiagBtn").addEventListener("click", copyDiagnostics);
  $("onboardingRestartBtn").addEventListener("click", () => startOnboarding(true));

  // ---- Configuration backup ----
  $("exportCfgBtn").addEventListener("click", exportConfig);
  $("exportCopyBtn").addEventListener("click", async () => {
    const ok = await copyText($("exportOut").value);
    toast(ok ? "Copied" : "Copy not available here");
  });
  $("importCfgBtn").addEventListener("click", () => $("importCfgFile").click());
  $("importCfgFile").addEventListener("change", (e) => {
    importConfigFile(e.target.files && e.target.files[0]);
    e.target.value = "";   // allow re-importing the same file
  });

  // ---- Onboarding ----
  $("obSkipBtn").addEventListener("click", () => closeOnboarding(true));
  loadHubInfo();   // available for the onboarding Hub step + About
  if (!onboardingDone()) startOnboarding();
}
document.addEventListener("DOMContentLoaded", init);)rgbwatt";