"""Regression tests for the exported default configuration.

The desktop shell bundles default-config.json (generated by
export_default_config.py during staging) so ZoneGlow.exe renders every Zones
and Settings field while the backend is offline. These tests pin the export's
completeness and determinism and guarantee it stays identical to the
AUTHORITATIVE defaults (pipeline.AppConfig / build_config_json - the faithful
port of the firmware's Config.cpp), so no second desktop copy can drift.
"""

import json
import os
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
EXPORTER = os.path.join(HERE, "..", "export_default_config.py")


def run_export(out_path):
    subprocess.check_call([sys.executable, EXPORTER, out_path])
    with open(out_path, encoding="utf-8") as f:
        return json.load(f)


class ExportDefaultConfigTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.handle, cls.path = tempfile.mkstemp(suffix=".json")
        os.close(cls.handle)
        cls.doc = run_export(cls.path)

    @classmethod
    def tearDownClass(cls):
        os.unlink(cls.path)

    def test_power_defaults_complete(self):
        self.assertEqual(self.doc["ftp"], 221)
        self.assertEqual(self.doc["zoneCount"], 7)
        self.assertEqual(len(self.doc["zones"]), 7)
        self.assertEqual(self.doc["zones"][0]["name"], "Z1 · Recovery")
        self.assertEqual(self.doc["zones"][-1]["name"], "Z7 · Neuromuscular")
        self.assertEqual(self.doc["zones"][0]["min"], 0)
        for z in self.doc["zones"]:
            self.assertTrue(z["color"].startswith("#"))

    def test_hr_defaults_complete(self):
        self.assertEqual(self.doc["hrMax"], 190)
        self.assertEqual(len(self.doc["hrZones"]), 5)
        self.assertEqual(self.doc["hrZones"][0]["name"], "Z1 · Recovery")
        self.assertEqual(self.doc["hrZones"][-1]["name"], "Z5 · Maximum")
        self.assertEqual(self.doc["hrZones"][-1]["max"], 190)

    def test_settings_defaults_complete(self):
        self.assertEqual(self.doc["smoothing"], 45)
        self.assertEqual(self.doc["powerTimeout"], 5000)
        self.assertEqual(self.doc["hysteresis"], 5)
        self.assertEqual(self.doc["ledPin"], 5)
        self.assertEqual(self.doc["ledCount"], 60)
        self.assertEqual(self.doc["ledType"], "WS2812B")
        self.assertEqual(self.doc["ledEffect"], 0)
        self.assertEqual(self.doc["brightness"], 100)
        self.assertTrue(self.doc["autoReconnect"])
        self.assertEqual(self.doc["controlSource"], "power")

    def test_export_is_deterministic(self):
        # Same authoritative source -> byte-identical file on every staging
        # run (CI diffs a fresh export against the bundled one).
        handle, path = tempfile.mkstemp(suffix=".json")
        os.close(handle)
        try:
            run_export(path)
            with open(path, "rb") as f:
                second = f.read()
            with open(self.path, "rb") as f:
                first = f.read()
            self.assertEqual(first, second)
        finally:
            os.unlink(path)


if __name__ == "__main__":
    unittest.main()
