// AUTO-GENERATED by tools/embed_web.py - do not edit by hand.
// Edit data/web/* and re-run the script.
#pragma once

const char INDEX_HTML[] = R"rgbwatt(
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <title>RGB Watt Controller</title>
  <link rel="stylesheet" href="/style.css" />
</head>
<body>
  <div class="app">
    <!-- Top bar -->
    <header class="topbar">
      <div class="brand">
        <span class="brand-dot" id="brandDot"></span>
        <div>
          <h1>RGB Watt</h1>
          <p class="brand-sub">Zone Controller</p>
        </div>
      </div>
      <div class="topbar-right">
        <span class="status-pill" id="statusPill" data-testid="status-pill">
          <span class="pill-dot"></span><span id="statusText">Starting</span>
        </span>
        <div class="theme-switch" id="themeSwitch">
          <button data-theme-val="light" data-testid="theme-light" title="Light">☀</button>
          <button data-theme-val="dark" data-testid="theme-dark" title="Dark">☾</button>
          <button data-theme-val="system" data-testid="theme-system" title="System">◐</button>
        </div>
      </div>
    </header>

    <!-- Nav -->
    <nav class="nav" id="nav">
      <button class="nav-btn active" data-view="dashboard" data-testid="nav-dashboard">Dashboard</button>
      <button class="nav-btn" data-view="source" data-testid="nav-source" id="navSourceBtn">Power Source</button>
      <button class="nav-btn" data-view="zones" data-testid="nav-zones">Zones</button>
      <button class="nav-btn" data-view="settings" data-testid="nav-settings">Settings</button>
    </nav>

    <main class="content">
      <!-- DASHBOARD -->
      <section class="view active" id="view-dashboard">
        <div class="grid">
          <div class="card power-card" id="powerCard" data-testid="power-card">
            <div class="power-glow" id="powerGlow"></div>
            <div class="power-value"><span id="powerWatts" data-testid="power-watts">0</span><em id="powerUnit">W</em></div>
            <div class="power-raw">Raw <span id="powerRaw">0</span> <span id="powerRawUnit">W</span></div>
            <div class="zone-badge" id="zoneBadge" data-testid="zone-badge">
              <span id="zoneNum">Z1</span> — <span id="zoneName">—</span>
            </div>
          </div>

          <div class="card source-mini" data-testid="source-mini">
            <div class="card-label" id="sourceMiniLabel">Power Source</div>
            <div class="source-name" id="dashSourceName">—</div>
            <div class="source-state" id="dashSourceState"><span class="pill-dot"></span><span>Disconnected</span></div>
          </div>

          <div class="card stat-row" data-testid="stat-row">
            <div class="stat"><div class="stat-k" id="statFtpLabel">FTP</div><div class="stat-v"><span id="statFtp">221</span> <span id="statFtpUnit">W</span></div></div>
            <div class="stat"><div class="stat-k">Zones</div><div class="stat-v" id="statZones">7</div></div>
            <div class="stat"><div class="stat-k">Brightness</div><div class="stat-v"><span id="statBright">100</span>%</div></div>
          </div>

          <div class="card sim-card" data-testid="sim-card">
            <div class="card-header">
              <div class="card-label">Simulation Mode</div>
              <label class="toggle">
                <input type="checkbox" id="simToggle" data-testid="sim-toggle" />
                <span class="toggle-track"></span>
              </label>
            </div>
            <p class="muted" id="simHint">Test the pipeline without a real device.</p>
            <input type="range" min="0" max="600" value="150" id="simSlider" class="slider" data-testid="sim-slider" disabled />
            <div class="sim-value"><span id="simVal">150</span> <span id="simUnit">W</span></div>
            <div class="sim-presets" id="simPresets"></div>
          </div>
        </div>
      </section>

      <!-- POWER SOURCE / HEART RATE SOURCE (adapts to the control source) -->
      <section class="view" id="view-source">
        <div class="card">
          <div class="card-header">
            <div>
              <div class="card-title" id="sourceTitle">Power Sources</div>
              <p class="muted" id="sourceSub">BLE Cycling Power Service devices (power meters &amp; smart trainers).</p>
            </div>
            <button class="btn primary" id="scanBtn" data-testid="scan-btn">Scan</button>
          </div>
          <div class="device-list" id="deviceList" data-testid="device-list">
            <div class="empty" id="deviceEmpty">No devices yet. Tap Scan to search.</div>
          </div>
        </div>
      </section>

      <!-- ZONES -->
      <section class="view" id="view-zones">
        <div class="card">
          <div class="card-header">
            <div class="card-title" id="zoneEditorTitle">Zone Editor</div>
            <button class="btn" id="resetZonesBtn" data-testid="reset-zones-btn">Reset to FTP defaults</button>
          </div>

          <!-- Power zone editor (Power mode only) -->
          <div id="powerZoneBlock">
            <div class="field-row">
              <div class="field">
                <label>FTP (W)</label>
                <input type="number" id="ftpInput" data-testid="ftp-input" min="50" max="600" />
              </div>
              <div class="field">
                <label>Zone Count</label>
                <select id="zoneCountSel" data-testid="zone-count-select">
                  <option value="5">5 Zones</option>
                  <option value="6">6 Zones</option>
                  <option value="7">7 Zones</option>
                </select>
              </div>
            </div>
            <div id="zoneEditor" class="zone-editor" data-testid="zone-editor"></div>
            <button class="btn primary full" id="saveZonesBtn" data-testid="save-zones-btn">Save Zones</button>
          </div>

          <!-- Heart Rate zone editor (Heart Rate mode only) -->
          <div id="hrZoneBlock" style="display:none">
            <div class="field-row">
              <div class="field">
                <label>Max HR (bpm)</label>
                <input type="number" id="hrMaxInput" data-testid="hr-max-input" min="100" max="230" />
              </div>
            </div>
            <div id="hrEditor" class="zone-editor" data-testid="hr-zone-editor"></div>
            <button class="btn primary full" id="saveHrZonesBtn" data-testid="save-hr-zones-btn">Save HR Zones</button>
          </div>
        </div>
      </section>

      <!-- SETTINGS -->
      <section class="view" id="view-settings">
        <div class="card">
          <div class="card-title">Control Source</div>
          <p class="muted">Only one source is active at a time. Switching disconnects the current sensor, stops its scan/reconnect logic and clears its live data.</p>
          <div class="seg" id="sourceSeg">
            <button data-src="power" class="active" data-testid="src-power">Power</button>
            <button data-src="hr" data-testid="src-hr">Heart Rate</button>
          </div>
        </div>

        <div class="card">
          <div class="card-title">Power Processing</div>
          <div class="field">
            <label>Smoothing <span class="val" id="smoothVal"></span></label>
            <input type="range" min="0" max="100" id="smoothInput" class="slider" data-testid="smoothing-input" />
          </div>
          <div class="field-row">
            <div class="field">
              <label>Power timeout (ms)</label>
              <input type="number" id="timeoutInput" data-testid="timeout-input" min="500" step="500" />
            </div>
            <div class="field">
              <label>Hysteresis (<span id="hysUnit">W</span>)</label>
              <input type="number" id="hysInput" data-testid="hysteresis-input" min="0" />
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-title">LED Strip</div>
          <div class="field-row">
            <div class="field">
              <label>GPIO Pin</label>
              <input type="number" id="ledPinInput" data-testid="led-pin-input" min="0" max="39" />
            </div>
            <div class="field">
              <label>LED Count</label>
              <input type="number" id="ledCountInput" data-testid="led-count-input" min="1" max="1000" />
            </div>
          </div>
          <div class="field-row">
            <div class="field">
              <label>LED Type</label>
              <select id="ledTypeSel" data-testid="led-type-select">
                <option value="WS2812B">WS2812B</option>
                <option value="SK6812">SK6812 (RGBW)</option>
              </select>
            </div>
            <div class="field">
              <label>Effect</label>
              <select id="ledEffectSel" data-testid="led-effect-select">
                <option value="0">Solid</option>
                <option value="1">Breathing</option>
                <option value="2">Comet</option>
              </select>
            </div>
          </div>
          <div class="field">
            <label>Brightness <span class="val" id="brightVal"></span></label>
            <input type="range" min="0" max="100" id="brightInput" class="slider" data-testid="brightness-input" />
          </div>
        </div>

        <div class="card">
          <div class="card-title">BLE</div>
          <div class="field switch-field">
            <label>Auto reconnect to saved source</label>
            <label class="toggle">
              <input type="checkbox" id="autoReconnect" data-testid="auto-reconnect-toggle" />
              <span class="toggle-track"></span>
            </label>
          </div>
          <div class="field switch-field">
            <label>Serial debug logging</label>
            <label class="toggle">
              <input type="checkbox" id="debugToggle" data-testid="debug-toggle" />
              <span class="toggle-track"></span>
            </label>
          </div>
        </div>

        <div class="card">
          <div class="card-title">Wi-Fi</div>
          <p class="muted">Connect the controller to your network. It reboots after saving.</p>
          <div class="field">
            <label>SSID</label>
            <input type="text" id="wifiSsid" data-testid="wifi-ssid-input" placeholder="Network name" />
          </div>
          <div class="field">
            <label>Password</label>
            <input type="password" id="wifiPass" data-testid="wifi-pass-input" placeholder="••••••••" />
          </div>
          <button class="btn primary" id="wifiSaveBtn" data-testid="wifi-save-btn">Save &amp; Reboot</button>
        </div>

        <div class="card">
          <div class="card-title">Firmware Update (OTA)</div>
          <p class="muted">Upload a compiled <code>firmware.bin</code> to flash wirelessly. The device reboots when done — don't close this page during upload.</p>
          <input type="file" id="otaFile" accept=".bin" data-testid="ota-file-input" />
          <div class="ota-progress" id="otaProgress"><div class="ota-bar" id="otaBar"></div></div>
          <button class="btn primary" id="otaBtn" data-testid="ota-upload-btn">Upload &amp; Flash</button>
        </div>

        <div class="card danger-card">
          <div class="card-title">Maintenance</div>
          <button class="btn" id="saveSettingsBtn" data-testid="save-settings-btn">Save Settings</button>
          <button class="btn danger" id="factoryBtn" data-testid="factory-reset-btn">Factory Reset</button>
        </div>
      </section>
    </main>

    <div class="toast" id="toast" data-testid="toast"></div>
  </div>
  <script src="/app.js"></script>
</body>
</html>)rgbwatt";

const char STYLE_CSS[] = R"rgbwatt(
:root {
  --bg: #f4f6fb;
  --bg-elev: #ffffff;
  --card: #ffffff;
  --text: #10131a;
  --muted: #6b7280;
  --border: #e5e8f0;
  --accent: #4f46e5;
  --accent-2: #06b6d4;
  --ok: #10b981;
  --warn: #f59e0b;
  --err: #ef4444;
  --shadow: 0 10px 30px rgba(20, 25, 60, 0.08);
  --radius: 18px;
  --font: "Segoe UI", "Helvetica Neue", system-ui, -apple-system, sans-serif;
}
[data-theme="dark"] {
  --bg: #0a0c12;
  --bg-elev: #12151f;
  --card: #151926;
  --text: #eef1f8;
  --muted: #8b93a7;
  --border: #232838;
  --accent: #7c7cff;
  --accent-2: #22d3ee;
  --shadow: 0 12px 40px rgba(0, 0, 0, 0.5);
}

* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { height: 100%; }
body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  -webkit-font-smoothing: antialiased;
  transition: background .3s ease, color .3s ease;
}
.app { max-width: 980px; margin: 0 auto; padding: 0 16px 80px; }

/* Top bar */
.topbar {
  display: flex; align-items: center; justify-content: space-between;
  padding: 20px 4px 12px;
}
.brand { display: flex; align-items: center; gap: 12px; }
.brand-dot {
  width: 40px; height: 40px; border-radius: 12px;
  background: linear-gradient(135deg, var(--accent), var(--accent-2));
  box-shadow: 0 0 24px rgba(124, 124, 255, .5);
  transition: background .4s ease, box-shadow .4s ease;
}
.brand h1 { font-size: 19px; letter-spacing: -.4px; }
.brand-sub { font-size: 12px; color: var(--muted); letter-spacing: 1.5px; text-transform: uppercase; }
.topbar-right { display: flex; align-items: center; gap: 10px; }

.status-pill {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 7px 13px; border-radius: 999px;
  background: var(--bg-elev); border: 1px solid var(--border);
  font-size: 13px; font-weight: 600;
}
.pill-dot { width: 9px; height: 9px; border-radius: 50%; background: var(--muted); }
.status-pill.ok .pill-dot { background: var(--ok); box-shadow: 0 0 10px var(--ok); }
.status-pill.warn .pill-dot { background: var(--warn); box-shadow: 0 0 10px var(--warn); }
.status-pill.err .pill-dot { background: var(--err); box-shadow: 0 0 10px var(--err); }
.status-pill.live .pill-dot { animation: pulse 1.4s infinite; background: var(--ok); }
@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.35} }

.theme-switch { display: flex; background: var(--bg-elev); border: 1px solid var(--border); border-radius: 999px; padding: 3px; }
.theme-switch button {
  border: none; background: transparent; color: var(--muted);
  width: 32px; height: 30px; border-radius: 999px; cursor: pointer; font-size: 15px;
  transition: all .2s;
}
.theme-switch button.active { background: var(--accent); color: #fff; }

/* Segmented control (Control Source) */
.seg { display: flex; gap: 6px; background: var(--bg-elev); border: 1px solid var(--border); padding: 6px; border-radius: 14px; margin-top: 12px; }
.seg button {
  flex: 1; border: none; background: transparent; color: var(--muted);
  padding: 11px 12px; border-radius: 10px; cursor: pointer; font-size: 14px; font-weight: 600;
  transition: all .2s;
}
.seg button.active { background: var(--accent); color: #fff; }

/* Nav */
.nav {
  display: flex; gap: 6px; margin: 6px 0 20px;
  background: var(--bg-elev); border: 1px solid var(--border);
  padding: 6px; border-radius: 14px; overflow-x: auto;
}
.nav-btn {
  flex: 1; min-width: 90px; border: none; background: transparent; color: var(--muted);
  padding: 10px 12px; border-radius: 10px; cursor: pointer; font-size: 14px; font-weight: 600;
  white-space: nowrap; transition: all .2s;
}
.nav-btn.active { background: var(--card); color: var(--text); box-shadow: var(--shadow); }

/* Views */
.view { display: none; animation: fade .35s ease; }
.view.active { display: block; }
@keyframes fade { from { opacity: 0; transform: translateY(8px);} to { opacity: 1; transform: none; } }

.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.card {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 20px; box-shadow: var(--shadow);
  margin-bottom: 16px;
}
.card-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 14px; }
.card-title { font-size: 16px; font-weight: 700; }
.card-label { font-size: 12px; text-transform: uppercase; letter-spacing: 1.2px; color: var(--muted); }
.muted { color: var(--muted); font-size: 13px; line-height: 1.5; }

/* Power card */
.power-card { grid-column: 1 / -1; position: relative; overflow: hidden; text-align: center; padding: 34px 20px 26px; }
.power-glow {
  position: absolute; top: -60px; left: 50%; transform: translateX(-50%);
  width: 320px; height: 320px; border-radius: 50%;
  background: radial-gradient(circle, rgba(124,124,255,.55), transparent 70%);
  filter: blur(30px); transition: background .3s ease; pointer-events: none;
}
.power-value { font-size: 84px; font-weight: 800; line-height: 1; letter-spacing: -3px; position: relative; }
.power-value em { font-size: 28px; font-style: normal; color: var(--muted); margin-left: 6px; font-weight: 600; }
.power-raw { color: var(--muted); font-size: 13px; margin-top: 6px; position: relative; }
.zone-badge {
  display: inline-block; margin-top: 16px; padding: 8px 18px; border-radius: 999px;
  background: var(--bg-elev); border: 1px solid var(--border); font-weight: 700; font-size: 15px; position: relative;
}

/* Source mini */
.source-mini { display: flex; flex-direction: column; gap: 8px; }
.source-name { font-size: 20px; font-weight: 700; }
.source-state { display: flex; align-items: center; gap: 8px; font-size: 13px; color: var(--muted); }

/* Stat row */
.stat-row { display: flex; justify-content: space-around; align-items: center; }
.stat { text-align: center; }
.stat-k { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 1px; }
.stat-v { font-size: 22px; font-weight: 700; margin-top: 4px; }

/* Sim */
.sim-card { grid-column: 1 / -1; }
.sim-value { text-align: center; font-size: 26px; font-weight: 700; margin: 6px 0 12px; }
.sim-presets { display: grid; grid-template-columns: repeat(9, 1fr); gap: 6px; }
.sim-presets button {
  border: 1px solid var(--border); background: var(--bg-elev); color: var(--text);
  padding: 8px 0; border-radius: 10px; cursor: pointer; font-weight: 600; font-size: 13px; transition: all .15s;
}
.sim-presets button:hover { border-color: var(--accent); color: var(--accent); }

/* Buttons */
.btn {
  border: 1px solid var(--border); background: var(--bg-elev); color: var(--text);
  padding: 11px 18px; border-radius: 12px; cursor: pointer; font-weight: 600; font-size: 14px;
  transition: all .2s;
}
.btn:hover { transform: translateY(-1px); border-color: var(--accent); }
.btn.primary { background: var(--accent); color: #fff; border-color: var(--accent); }
.btn.primary:hover { filter: brightness(1.08); }
.btn.danger { background: transparent; color: var(--err); border-color: var(--err); }
.btn.full { width: 100%; margin-top: 8px; }

/* Fields */
.field { margin-bottom: 16px; }
.field label { display: block; font-size: 13px; font-weight: 600; margin-bottom: 8px; color: var(--muted); }
.field .val { color: var(--accent); float: right; }
.field-row { display: flex; gap: 14px; }
.field-row .field { flex: 1; }
.switch-field { display: flex; align-items: center; justify-content: space-between; }
.switch-field label:first-child { margin: 0; color: var(--text); font-weight: 600; }
input[type="text"], input[type="number"], input[type="password"], select {
  width: 100%; padding: 12px 14px; border-radius: 12px;
  border: 1px solid var(--border); background: var(--bg-elev); color: var(--text);
  font-size: 15px; font-family: var(--font); outline: none; transition: border .2s;
}
input:focus, select:focus { border-color: var(--accent); }

/* Sliders */
.slider { -webkit-appearance: none; appearance: none; width: 100%; height: 8px; border-radius: 999px; background: var(--border); outline: none; }
.slider::-webkit-slider-thumb { -webkit-appearance: none; width: 22px; height: 22px; border-radius: 50%; background: var(--accent); cursor: pointer; box-shadow: 0 2px 8px rgba(0,0,0,.3); }
.slider::-moz-range-thumb { width: 22px; height: 22px; border: none; border-radius: 50%; background: var(--accent); cursor: pointer; }
.slider:disabled { opacity: .5; }

/* Toggle */
.toggle { position: relative; display: inline-block; width: 46px; height: 26px; }
.toggle input { display: none; }
.toggle-track { position: absolute; inset: 0; background: var(--border); border-radius: 999px; transition: .25s; cursor: pointer; }
.toggle-track:before { content: ""; position: absolute; width: 20px; height: 20px; left: 3px; top: 3px; background: #fff; border-radius: 50%; transition: .25s; }
.toggle input:checked + .toggle-track { background: var(--accent); }
.toggle input:checked + .toggle-track:before { transform: translateX(20px); }

/* Device list */
.device-list { display: flex; flex-direction: column; gap: 10px; }
.empty { color: var(--muted); font-size: 14px; text-align: center; padding: 24px; }
.device {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  padding: 14px 16px; border: 1px solid var(--border); border-radius: 14px; background: var(--bg-elev);
}
.device-info { display: flex; align-items: center; gap: 12px; min-width: 0; }
.device-radio { width: 12px; height: 12px; border-radius: 50%; border: 2px solid var(--muted); flex-shrink: 0; }
.device.connected .device-radio { border-color: var(--ok); background: var(--ok); box-shadow: 0 0 10px var(--ok); }
.device-meta { min-width: 0; }
.device-name { font-weight: 700; font-size: 15px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.device-addr { font-size: 12px; color: var(--muted); }
.device-actions { display: flex; gap: 8px; flex-shrink: 0; }
.badge { display: inline-block; font-size: 10px; font-weight: 700; letter-spacing: .5px; padding: 2px 7px; border-radius: 6px; background: var(--accent); color: #fff; vertical-align: middle; }

/* OTA */
.ota-progress { height: 8px; border-radius: 999px; background: var(--border); overflow: hidden; margin: 14px 0; }
.ota-bar { height: 100%; width: 0%; background: linear-gradient(90deg, var(--accent), var(--accent-2)); transition: width .2s; }
input[type="file"] { width: 100%; font-size: 13px; color: var(--muted); }

/* Zone editor */
.zone-editor { display: flex; flex-direction: column; gap: 12px; margin: 8px 0 16px; }
.zone-item {
  display: grid; grid-template-columns: 46px 1fr 90px 90px 46px; gap: 10px; align-items: center;
  padding: 12px; border: 1px solid var(--border); border-radius: 14px; background: var(--bg-elev);
}
.zone-color { width: 46px; height: 46px; border-radius: 10px; border: none; cursor: pointer; padding: 0; background: none; }
.zone-item input[type="text"], .zone-item input[type="number"] { padding: 9px 10px; font-size: 14px; }
.zone-swatch { width: 46px; height: 46px; border-radius: 10px; }
.zone-item .zlabel { font-size: 11px; color: var(--muted); }

/* Toast */
.toast {
  position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%) translateY(20px);
  background: var(--text); color: var(--bg); padding: 13px 22px; border-radius: 12px;
  font-weight: 600; font-size: 14px; opacity: 0; pointer-events: none; transition: all .3s; z-index: 50;
}
.toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }

@media (max-width: 640px) {
  .grid { grid-template-columns: 1fr; }
  .power-value { font-size: 66px; }
  .sim-presets { grid-template-columns: repeat(5, 1fr); }
  .zone-item { grid-template-columns: 40px 1fr 70px; grid-auto-rows: auto; }
  .zone-item .zmax { display: none; }
  .field-row { flex-direction: column; gap: 0; }
})rgbwatt";

const char APP_JS[] = R"rgbwatt(
// ESP32 RGB Watt Zone Controller - Web UI
"use strict";

const $ = (id) => document.getElementById(id);
let config = null;
let ws = null;
let simState = { enabled: false, watts: 150, bpm: 120 };

function isHrMode() { return !!(config && config.controlSource === "hr"); }

// ---------------- Theme ----------------
function applyTheme(theme) {
  let effective = theme;
  if (theme === "system") {
    effective = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  }
  document.documentElement.setAttribute("data-theme", effective);
  document.querySelectorAll("#themeSwitch button").forEach((b) => {
    b.classList.toggle("active", b.dataset.themeVal === theme);
  });
}
function initTheme() {
  const saved = localStorage.getItem("theme") || "system";
  applyTheme(saved);
  document.querySelectorAll("#themeSwitch button").forEach((b) => {
    b.addEventListener("click", () => {
      const t = b.dataset.themeVal;
      localStorage.setItem("theme", t);
      applyTheme(t);
      if (config) { config.theme = t; postConfig({ theme: t }); }
    });
  });
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", () => {
    if ((localStorage.getItem("theme") || "system") === "system") applyTheme("system");
  });
}

// ---------------- Toast ----------------
let toastTimer = null;
function toast(msg) {
  const t = $("toast");
  t.textContent = msg;
  t.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => t.classList.remove("show"), 2200);
}

// ---------------- Nav ----------------
function initNav() {
  document.querySelectorAll(".nav-btn").forEach((b) => {
    b.addEventListener("click", () => {
      document.querySelectorAll(".nav-btn").forEach((x) => x.classList.remove("active"));
      document.querySelectorAll(".view").forEach((v) => v.classList.remove("active"));
      b.classList.add("active");
      $("view-" + b.dataset.view).classList.add("active");
      if (b.dataset.view === "source") refreshDevices();
    });
  });
}

// ---------------- API ----------------
async function getConfig() {
  const r = await fetch("/api/config");
  config = await r.json();
  return config;
}
async function postConfig(patch) {
  const r = await fetch("/api/config", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  config = await r.json();
  return config;
}

// ---------------- Control source ----------------
function initSourceSeg() {
  document.querySelectorAll("#sourceSeg button").forEach((b) => {
    b.addEventListener("click", async () => {
      if (b.classList.contains("active")) return;
      await postConfig({ controlSource: b.dataset.src });
      // The device disconnected the previous sensor and cleared its state;
      // reset the local simulation UI to match.
      simState.enabled = false;
      fillForms();
      toast(isHrMode() ? "Switched to Heart Rate mode" : "Switched to Power mode");
    });
  });
}

// ---------------- Populate forms ----------------
function fillForms() {
  $("ftpInput").value = config.ftp;
  $("zoneCountSel").value = config.zoneCount;
  $("smoothInput").value = config.smoothing;
  $("smoothVal").textContent = config.smoothing;
  $("timeoutInput").value = config.powerTimeout;
  $("hysInput").value = config.hysteresis;
  $("ledPinInput").value = config.ledPin;
  $("ledCountInput").value = config.ledCount;
  $("ledTypeSel").value = config.ledType;
  $("ledEffectSel").value = config.ledEffect;
  $("brightInput").value = config.brightness;
  $("brightVal").textContent = config.brightness + "%";
  $("autoReconnect").checked = config.autoReconnect;
  $("debugToggle").checked = config.debug;
  $("wifiSsid").value = config.wifiSsid || "";
  if (config.hrMax) $("hrMaxInput").value = config.hrMax;

  // ---- UI adapts to the active control source ----
  const hr = isHrMode();
  $("statFtpLabel").textContent = hr ? "Max HR" : "FTP";
  $("statFtp").textContent = hr ? config.hrMax : config.ftp;
  $("statFtpUnit").textContent = hr ? "bpm" : "W";
  $("statZones").textContent = hr ? (config.hrZones ? config.hrZones.length : 5) : config.zoneCount;
  $("powerUnit").textContent = hr ? "BPM" : "W";
  $("powerRawUnit").textContent = hr ? "bpm" : "W";
  $("simUnit").textContent = hr ? "bpm" : "W";
  $("hysUnit").textContent = hr ? "bpm" : "W";
  $("powerZoneBlock").style.display = hr ? "none" : "";
  $("hrZoneBlock").style.display = hr ? "" : "none";
  $("resetZonesBtn").textContent = hr ? "Reset to Max HR defaults" : "Reset to FTP defaults";
  $("sourceTitle").textContent = hr ? "Heart Rate Sensors" : "Power Sources";
  $("sourceSub").textContent = hr
    ? "BLE Heart Rate Service devices (chest straps & watches)."
    : "BLE Cycling Power Service devices (power meters & smart trainers).";
  $("sourceMiniLabel").textContent = hr ? "Heart Rate Source" : "Power Source";
  $("navSourceBtn").textContent = hr ? "HR Sensors" : "Power Source";
  document.querySelectorAll("#sourceSeg button").forEach((b) => {
    b.classList.toggle("active", (b.dataset.src === "hr") === hr);
  });

  renderZoneEditor();
  renderHrZoneEditor();
  renderSimControls();
}

// ---------------- Power zone editor ----------------
function renderZoneEditor() {
  const el = $("zoneEditor");
  el.innerHTML = "";
  if (!config.zones) return;
  config.zones.forEach((z, i) => {
    el.appendChild(zoneRow(z, i, "zone", (i < config.zones.length - 1)));
  });
  bindZoneEditor(el, config.zones);
}

// ---------------- HR zone editor ----------------
function renderHrZoneEditor() {
  const el = $("hrEditor");
  el.innerHTML = "";
  if (!config.hrZones) return;
  config.hrZones.forEach((z, i) => {
    el.appendChild(zoneRow(z, i, "hr-zone", (i < config.hrZones.length - 1)));
  });
  bindZoneEditor(el, config.hrZones);
}

function zoneRow(z, i, testPrefix, hasMax) {
  const row = document.createElement("div");
  row.className = "zone-item";
  const maxLabel = !hasMax || z.max < 0 ? "∞" : z.max;
  row.innerHTML =
    '<input type="color" class="zone-color" value="' + z.color + '" data-i="' + i + '" data-testid="' + testPrefix + '-color-' + i + '" />' +
    '<div><div class="zlabel">Zone ' + (i + 1) + ' name</div>' +
      '<input type="text" class="zone-name" value="' + escapeAttr(z.name) + '" data-i="' + i + '" data-testid="' + testPrefix + '-name-' + i + '" /></div>' +
    '<div><div class="zlabel">Min ' + (testPrefix === "hr-zone" ? "bpm" : "W") + '</div>' +
      '<input type="number" class="zone-min" value="' + z.min + '" data-i="' + i + '" data-testid="' + testPrefix + '-min-' + i + '" /></div>' +
    '<div class="zmax"><div class="zlabel">Max ' + (testPrefix === "hr-zone" ? "bpm" : "W") + '</div>' +
      '<input type="number" value="' + (hasMax && z.max >= 0 ? z.max : "") + '" disabled placeholder="' + maxLabel + '" /></div>' +
    '<div class="zone-swatch" style="background:' + z.color + '"></div>';
  return row;
}

function bindZoneEditor(el, zones) {
  el.querySelectorAll(".zone-color").forEach((c) =>
    c.addEventListener("input", (e) => {
      const i = +e.target.dataset.i;
      e.target.parentElement.querySelector(".zone-swatch").style.background = e.target.value;
      zones[i].color = e.target.value;
    })
  );
}
function escapeAttr(s) { return (s || "").replace(/"/g, "&quot;"); }

async function saveZones() {
  const zones = config.zones.map((z, i) => ({
    name: $("zoneEditor").querySelectorAll(".zone-name")[i].value,
    min: +$("zoneEditor").querySelectorAll(".zone-min")[i].value,
    color: $("zoneEditor").querySelectorAll(".zone-color")[i].value,
  }));
  await postConfig({ ftp: +$("ftpInput").value, zones: zones });
  fillForms();
  toast("Zones saved");
}

async function saveHrZones() {
  const zones = config.hrZones.map((z, i) => ({
    name: $("hrEditor").querySelectorAll(".zone-name")[i].value,
    min: +$("hrEditor").querySelectorAll(".zone-min")[i].value,
    color: $("hrEditor").querySelectorAll(".zone-color")[i].value,
  }));
  await postConfig({ hrZones: zones });
  fillForms();
  toast("HR zones saved");
}

async function onZoneCountChange() {
  await postConfig({ zoneCount: +$("zoneCountSel").value, ftp: +$("ftpInput").value });
  fillForms();
  toast("Zone model updated");
}
async function resetZones() {
  if (isHrMode()) {
    await postConfig({ hrZonesReset: true });
    fillForms();
    toast("HR zones reset to Max HR defaults");
  } else {
    await postConfig({ zoneCount: +$("zoneCountSel").value, ftp: +$("ftpInput").value });
    fillForms();
    toast("Zones reset to FTP defaults");
  }
}

// ---------------- Settings ----------------
async function saveSettings() {
  await postConfig({
    smoothing: +$("smoothInput").value,
    powerTimeout: +$("timeoutInput").value,
    hysteresis: +$("hysInput").value,
    ledPin: +$("ledPinInput").value,
    ledCount: +$("ledCountInput").value,
    ledType: $("ledTypeSel").value,
    ledEffect: +$("ledEffectSel").value,
    brightness: +$("brightInput").value,
    autoReconnect: $("autoReconnect").checked,
    debug: $("debugToggle").checked,
  });
  fillForms();
  toast("Settings saved");
}
async function saveWifi() {
  const ssid = $("wifiSsid").value.trim();
  if (!ssid) { toast("Enter an SSID"); return; }
  await fetch("/api/wifi", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ssid: ssid, pass: $("wifiPass").value }),
  });
  toast("Saved. Rebooting — reconnect to your network.");
}
async function factoryReset() {
  if (!confirm("Reset all settings to factory defaults?")) return;
  await fetch("/api/factory-reset", { method: "POST" });
  toast("Factory reset — rebooting…");
}

// ---------------- OTA ----------------
function otaUpload() {
  const f = $("otaFile").files[0];
  if (!f) { toast("Choose a firmware .bin first"); return; }
  const bar = $("otaBar");
  const btn = $("otaBtn");
  btn.disabled = true;
  bar.style.width = "0%";
  const fd = new FormData();
  fd.append("firmware", f, f.name);
  const xhr = new XMLHttpRequest();
  xhr.open("POST", "/api/ota");
  xhr.upload.onprogress = (e) => {
    if (e.lengthComputable) bar.style.width = Math.round((e.loaded / e.total) * 100) + "%";
  };
  xhr.onload = () => {
    let ok = false;
    try { ok = JSON.parse(xhr.responseText).ok; } catch (_) {}
    if (ok) { bar.style.width = "100%"; toast("Firmware flashed — rebooting…"); }
    else { toast("Update failed"); btn.disabled = false; }
  };
  xhr.onerror = () => { toast("Upload error"); btn.disabled = false; };
  xhr.send(fd);
  toast("Uploading firmware…");
}

// ---------------- Power / HR Source ----------------
let deviceTimer = null;
async function scan() {
  await fetch("/api/scan", { method: "POST" });
  $("scanBtn").textContent = "Scanning…";
  $("scanBtn").disabled = true;
  toast("Scanning for " + (isHrMode() ? "heart rate sensors…" : "power sources…"));
  let ticks = 0;
  clearInterval(deviceTimer);
  deviceTimer = setInterval(async () => {
    await refreshDevices();
    if (++ticks > 8) {
      clearInterval(deviceTimer);
      $("scanBtn").textContent = "Scan";
      $("scanBtn").disabled = false;
    }
  }, 1000);
}
async function refreshDevices() {
  const r = await fetch("/api/devices");
  const data = await r.json();
  const list = $("deviceList");
  if (!data.devices || data.devices.length === 0) {
    list.innerHTML = '<div class="empty">' + (data.scanning ? "Scanning…" : "No devices found. Tap Scan.") + "</div>";
    return;
  }
  list.innerHTML = "";
  data.devices.forEach((d) => {
    const row = document.createElement("div");
    row.className = "device" + (d.connected ? " connected" : "");
    row.innerHTML =
      '<div class="device-info">' +
        '<span class="device-radio"></span>' +
        '<div class="device-meta">' +
          '<div class="device-name">' + escapeHtml(d.name) + (d.type ? ' <span class="badge">' + d.type + '</span>' : "") + "</div>" +
          '<div class="device-addr">' + d.address + "  ·  " + d.rssi + " dBm</div>" +
        "</div></div>" +
      '<div class="device-actions"></div>';
    const actions = row.querySelector(".device-actions");
    if (d.connected) {
      actions.appendChild(mkBtn("Disconnect", "", () => disconnect()));
      actions.appendChild(mkBtn("Forget", "danger", () => forget()));
    } else {
      actions.appendChild(mkBtn("Connect", "primary", () => connect(d.address, d.name)));
    }
    list.appendChild(row);
  });
}
function mkBtn(label, cls, fn) {
  const b = document.createElement("button");
  b.className = "btn " + cls;
  b.textContent = label;
  b.setAttribute("data-testid", "device-" + label.toLowerCase() + "-btn");
  b.addEventListener("click", fn);
  return b;
}
async function connect(address, name) {
  await fetch("/api/connect", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ address: address, name: name }),
  });
  toast("Connecting to " + name + "…");
  setTimeout(refreshDevices, 1200);
}
async function disconnect() { await fetch("/api/disconnect", { method: "POST" }); toast("Disconnected"); setTimeout(refreshDevices, 600); }
async function forget() { await fetch("/api/forget", { method: "POST" }); toast("Source forgotten"); setTimeout(refreshDevices, 600); }
function escapeHtml(s) { const d = document.createElement("div"); d.textContent = s; return d.innerHTML; }

// ---------------- Simulation ----------------
function initSim() {
  $("simToggle").addEventListener("change", () => {
    simState.enabled = $("simToggle").checked;
    $("simSlider").disabled = !simState.enabled;
    pushSim();
    toast(simState.enabled ? "Simulation ON" : "Simulation OFF");
  });
  $("simSlider").addEventListener("input", () => {
    if (isHrMode()) {
      simState.bpm = +$("simSlider").value;
      $("simVal").textContent = simState.bpm;
    } else {
      simState.watts = +$("simSlider").value;
      $("simVal").textContent = simState.watts;
    }
    pushSim();
  });
}

function renderSimControls() {
  const slider = $("simSlider");
  if (isHrMode()) {
    slider.min = 40;
    slider.max = 220;
    if (!simState.enabled) simState.bpm = Math.min(220, Math.max(40, simState.bpm || 120));
    slider.value = simState.bpm;
    $("simVal").textContent = simState.bpm;
    // Presets covering all 5 HR zones, derived from the configured boundaries.
    const mins = (config.hrZones || []).map((z) => z.min);
    const presets = [];
    if (mins.length === 5) {
      presets.push(Math.max(40, mins[0] - 10), mins[0] + 5, mins[1] + 5, mins[2] + 5, mins[3] + 5, mins[4] + 5, (config.hrMax || 190) + 10);
    }
    renderSimPresets(presets, true);
  } else {
    slider.min = 0;
    slider.max = 600;
    if (!simState.enabled) simState.watts = 150;
    slider.value = simState.watts;
    $("simVal").textContent = simState.watts;
    renderSimPresets([0, 50, 100, 150, 200, 250, 300, 400, 500], false);
  }
  slider.disabled = !simState.enabled;
  $("simToggle").checked = simState.enabled;
}

function renderSimPresets(values, hr) {
  const box = $("simPresets");
  box.innerHTML = "";
  const seen = {};
  values.forEach((v) => {
    v = Math.round(v);
    if (seen[v] || v < (hr ? 40 : 0) || v > (hr ? 220 : 600)) return;
    seen[v] = true;
    const b = document.createElement("button");
    b.textContent = v;
    b.addEventListener("click", () => {
      if (hr) simState.bpm = v; else simState.watts = v;
      if (!simState.enabled) simState.enabled = true;
      $("simSlider").value = v;
      $("simVal").textContent = v;
      $("simSlider").disabled = false;
      $("simToggle").checked = true;
      pushSim();
    });
    box.appendChild(b);
  });
}

let simTimer = null;
function pushSim() {
  clearTimeout(simTimer);
  simTimer = setTimeout(() => {
    const body = { enabled: simState.enabled };
    if (isHrMode()) body.bpm = simState.bpm;
    else body.watts = simState.watts;
    fetch("/api/simulation", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
  }, 80);
}

// ---------------- WebSocket telemetry ----------------
function initWs() {
  const proto = location.protocol === "https:" ? "wss" : "ws";
  ws = new WebSocket(proto + "://" + location.host + "/ws");
  ws.onmessage = (e) => { try { updateLive(JSON.parse(e.data)); } catch (_) {} };
  ws.onclose = () => setTimeout(initWs, 2000);
}
const STATE_MAP = {
  RECEIVING_POWER: { cls: "live", label: "Receiving Data" },
  CONNECTED: { cls: "ok", label: "Connected" },
  CONNECTING: { cls: "warn", label: "Connecting" },
  RECONNECTING: { cls: "warn", label: "Reconnecting" },
  SCANNING: { cls: "warn", label: "Scanning" },
  DISCONNECTED: { cls: "", label: "Disconnected" },
  STARTING: { cls: "", label: "Starting" },
  ERROR: { cls: "err", label: "Error" },
};
function updateLive(t) {
  $("powerWatts").textContent = t.smoothed;
  $("powerRaw").textContent = t.raw;
  $("zoneNum").textContent = "Z" + (t.zone + 1);
  $("zoneName").textContent = t.zoneName || "—";
  const s = STATE_MAP[t.state] || STATE_MAP.STARTING;
  const pill = $("statusPill");
  pill.className = "status-pill " + s.cls;
  $("statusText").textContent = t.sim ? "Simulation" : s.label;

  // Colour glow + brand: must show the SAME zone as the label. Use the current
  // zone's configured colour of the ACTIVE control source so
  // zone number = zone name = displayed colour.
  const hr = (t.mode || (config && config.controlSource)) === "hr";
  const zones = hr ? (config.hrZones || []) : (config.zones || []);
  const zoneColor = (t.zone >= 0 && t.zone < zones.length) ? zones[t.zone].color : t.color;
  $("powerGlow").style.background = "radial-gradient(circle, " + zoneColor + "cc, transparent 70%)";
  $("brandDot").style.background = zoneColor;
  $("brandDot").style.boxShadow = "0 0 24px " + zoneColor + "88";

  // Dashboard source
  $("dashSourceName").textContent = t.source || (t.sim ? "Simulation" : "—");
  const ds = $("dashSourceState");
  ds.querySelector("span:last-child").textContent = t.sim ? "Simulated" : s.label;
  ds.querySelector(".pill-dot").style.background = s.cls === "live" || s.cls === "ok" ? "var(--ok)" : "var(--muted)";
}

// ---------------- Init ----------------
async function init() {
  initTheme();
  initNav();
  initSim();
  await getConfig();
  // Sync stored theme with device config (device is source of truth on first load if set)
  if (config.theme && !localStorage.getItem("theme")) { localStorage.setItem("theme", config.theme); applyTheme(config.theme); }
  fillForms();
  initWs();

  $("ftpInput").addEventListener("change", async () => { await postConfig({ ftp: +$("ftpInput").value }); fillForms(); toast("FTP updated"); });
  $("hrMaxInput").addEventListener("change", async () => { await postConfig({ hrMax: +$("hrMaxInput").value }); fillForms(); toast("Max HR updated"); });
  $("zoneCountSel").addEventListener("change", onZoneCountChange);
  $("saveZonesBtn").addEventListener("click", saveZones);
  $("saveHrZonesBtn").addEventListener("click", saveHrZones);
  $("resetZonesBtn").addEventListener("click", resetZones);
  $("saveSettingsBtn").addEventListener("click", saveSettings);
  $("wifiSaveBtn").addEventListener("click", saveWifi);
  $("factoryBtn").addEventListener("click", factoryReset);
  $("otaBtn").addEventListener("click", otaUpload);
  $("ledEffectSel").addEventListener("change", async () => { await postConfig({ ledEffect: +$("ledEffectSel").value }); toast("Effect updated"); });
  $("scanBtn").addEventListener("click", scan);
  $("smoothInput").addEventListener("input", () => ($("smoothVal").textContent = $("smoothInput").value));
  $("brightInput").addEventListener("input", () => ($("brightVal").textContent = $("brightInput").value + "%"));
}
document.addEventListener("DOMContentLoaded", init);)rgbwatt";
